C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapdt_rndm (dt_rndmf2pywrap, vdummy)
      external dt_rndm
      double precision vdummy
      double precision dt_rndmf2pywrap, dt_rndm
      dt_rndmf2pywrap = dt_rndm(vdummy)
      end


      subroutine f2pywrapidt_icihad (idt_icihadf2pywrap, mcind)
      external idt_icihad
      integer mcind
      integer idt_icihadf2pywrap, idt_icihad
      idt_icihadf2pywrap = idt_icihad(mcind)
      end


      subroutine f2pywrapidt_ipdgha (idt_ipdghaf2pywrap, mcind)
      external idt_ipdgha
      integer mcind
      integer idt_ipdghaf2pywrap, idt_ipdgha
      idt_ipdghaf2pywrap = idt_ipdgha(mcind)
      end


      subroutine f2pywrapipho_id2pdg (ipho_id2pdgf2pywrap, idcpc)
      external ipho_id2pdg
      integer idcpc
      integer ipho_id2pdgf2pywrap, ipho_id2pdg
      ipho_id2pdgf2pywrap = ipho_id2pdg(idcpc)
      end


      subroutine f2pywrapipho_pdg2id (ipho_pdg2idf2pywrap, idpdg)
      external ipho_pdg2id
      integer idpdg
      integer ipho_pdg2idf2pywrap, ipho_pdg2id
      ipho_pdg2idf2pywrap = ipho_pdg2id(idpdg)
      end


      subroutine f2pywrappho_pmass (pho_pmassf2pywrap, id, mode)
      external pho_pmass
      integer id
      integer mode
      double precision pho_pmassf2pywrap, pho_pmass
      pho_pmassf2pywrap = pho_pmass(id, mode)
      end


      subroutine f2pywrappho_pname (pho_pnamef2pywrap, id, mode)
      external pho_pname
      integer id
      integer mode
      character*15 pho_pnamef2pywrap, pho_pname
      pho_pnamef2pywrap = pho_pname(id, mode)
      end


      subroutine f2pywrappho_ptcut (pho_ptcutf2pywrap, ecm, ip)
      external pho_ptcut
      double precision ecm
      integer ip
      double precision pho_ptcutf2pywrap, pho_ptcut
      pho_ptcutf2pywrap = pho_ptcut(ecm, ip)
      end


      subroutine f2pywrappycomp (pycompf2pywrap, kf)
      external pycomp
      integer kf
      integer pycompf2pywrap, pycomp
      pycompf2pywrap = pycomp(kf)
      end


      subroutine f2pyinitdtrand(setupfunc)
      external setupfunc
      double precision u(97)
      double precision c
      double precision cd
      double precision cm
      integer i
      integer j
      common /dtrand/ u,c,cd,cm,i,j
      call setupfunc(u,c,cd,cm,i,j)
      end


