C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.23.5)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinithnreac(setupfunc)
      external setupfunc
      double precision umo(296)
      double precision plabf(296)
      double precision siin(296)
      double precision wk(5184)
      integer nrk(2,268)
      integer nure(30,2)
      common /hnreac/ umo,plabf,siin,wk,nrk,nure
      call setupfunc(umo,plabf,siin,wk,nrk,nure)
      end


