C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapipho_id2pdg (ipho_id2pdgf2pywrap, idcpc)
      external ipho_id2pdg
      integer idcpc
      integer ipho_id2pdgf2pywrap, ipho_id2pdg
      ipho_id2pdgf2pywrap = ipho_id2pdg(idcpc)
      end


      subroutine f2pywrapipho_pdg2id (ipho_pdg2idf2pywrap, idpdg)
      external ipho_pdg2id
      integer idpdg
      integer ipho_pdg2idf2pywrap, ipho_pdg2id
      ipho_pdg2idf2pywrap = ipho_pdg2id(idpdg)
      end


      subroutine f2pywrappho_pmass (pho_pmassf2pywrap, id, mode)
      external pho_pmass
      integer id
      integer mode
      double precision pho_pmassf2pywrap, pho_pmass
      pho_pmassf2pywrap = pho_pmass(id, mode)
      end


      subroutine f2pywrappho_pname (pho_pnamef2pywrap, id, mode)
      external pho_pname
      integer id
      integer mode
      character*15 pho_pnamef2pywrap, pho_pname
      pho_pnamef2pywrap = pho_pname(id, mode)
      end


      subroutine f2pywrappho_ptcut (pho_ptcutf2pywrap, ecm, ip)
      external pho_ptcut
      double precision ecm
      integer ip
      double precision pho_ptcutf2pywrap, pho_ptcut
      pho_ptcutf2pywrap = pho_ptcut(ecm, ip)
      end


      subroutine f2pywrappycomp (pycompf2pywrap, kf)
      external pycomp
      integer kf
      integer pycompf2pywrap, pycomp
      pycompf2pywrap = pycomp(kf)
      end


      subroutine f2pyinithnreac(setupfunc)
      external setupfunc
      double precision umo(296)
      double precision plabf(296)
      double precision siin(296)
      double precision wk(5184)
      integer nrk(2,268)
      integer nure(30,2)
      common /hnreac/ umo,plabf,siin,wk,nrk,nure
      call setupfunc(umo,plabf,siin,wk,nrk,nure)
      end

      subroutine f2pyinitdtpart(setupfunc)
      external setupfunc
      character aname(210,8)
      double precision aam(210)
      double precision ga(210)
      double precision tau(210)
      integer iich(210)
      integer iibar(210)
      integer k1(210)
      integer k2(210)
      common /dtpart/ aname,aam,ga,tau,iich,iibar,k1,k2
      call setupfunc(aname,aam,ga,tau,iich,iibar,k1,k2)
      end

      subroutine f2pyinithndech(setupfunc)
      external setupfunc
      character zkname(602,8)
      double precision wt(602)
      integer nzk(602,3)
      common /hndech/ zkname,wt,nzk
      call setupfunc(zkname,wt,nzk)
      end

      subroutine f2pyinitdtflg1(setupfunc)
      external setupfunc
      integer ifrag(2)
      integer iresco
      integer imshl
      integer iresrj
      integer ioulev(6)
      logical lemcck
      logical lhadro(10)
      logical lseadi
      logical levapo
      integer iframe
      integer itrspt
      integer ifusion
      integer iflow
      common /dtflg1/ ifrag,iresco,imshl,iresrj,ioulev,lemcck,lhad
     &ro,lseadi,levapo,iframe,itrspt,ifusion,iflow
      call setupfunc(ifrag,iresco,imshl,iresrj,ioulev,lemcck,lhadr
     &o,lseadi,levapo,iframe,itrspt,ifusion,iflow)
      end

      subroutine f2pyinitdtcomp(setupfunc)
      external setupfunc
      double precision emufra(100)
      integer iemuma(100)
      integer iemuch(100)
      integer ncompo
      integer iemul
      common /dtcomp/ emufra,iemuma,iemuch,ncompo,iemul
      call setupfunc(emufra,iemuma,iemuch,ncompo,iemul)
      end

      subroutine f2pyinitdtflka(setupfunc)
      external setupfunc
      integer linp
      integer lout
      integer ldat
      integer lpri
      common /dtflka/ linp,lout,ldat,lpri
      call setupfunc(linp,lout,ldat,lpri)
      end

      subroutine f2pyinitdtquar(setupfunc)
      external setupfunc
      integer iqechr(13)
      integer iqbchr(13)
      integer iqichr(13)
      integer iqschr(13)
      integer iqcchr(13)
      integer iquchr(13)
      integer iqtchr(13)
      integer mquark(3,39)
      common /dtquar/ iqechr,iqbchr,iqichr,iqschr,iqcchr,iquchr,iq
     &tchr,mquark
      call setupfunc(iqechr,iqbchr,iqichr,iqschr,iqcchr,iquchr,iqt
     &chr,mquark)
      end

      subroutine f2pyinitdthaic(setupfunc)
      external setupfunc
      integer ipdg2(2,7)
      integer ibam2(2,7)
      integer ipdg3(2,22)
      integer ibam3(2,22)
      integer ipdg4(2,29)
      integer ibam4(2,29)
      integer ipdg5(2,19)
      integer ibam5(2,19)
      integer iamcin(210)
      common /dthaic/ ipdg2,ibam2,ipdg3,ibam3,ipdg4,ibam4,ipdg5,ib
     &am5,iamcin
      call setupfunc(ipdg2,ibam2,ipdg3,ibam3,ipdg4,ibam4,ipdg5,iba
     &m5,iamcin)
      end

      subroutine f2pyinitdtpain(setupfunc)
      external setupfunc
      character btype(30,8)
      common /dtpain/ btype
      call setupfunc(btype)
      end

      subroutine f2pyinithnslop(setupfunc)
      external setupfunc
      double precision sm(25)
      double precision bbm(25)
      double precision bbb(25)
      common /hnslop/ sm,bbm,bbb
      call setupfunc(sm,bbm,bbb)
      end

      subroutine f2pyinithnredv(setupfunc)
      external setupfunc
      double precision thresh(268)
      integer irii(17)
      integer ikii(17)
      integer ieii(17)
      common /hnredv/ thresh,irii,ikii,ieii
      call setupfunc(thresh,irii,ikii,ieii)
      end

      subroutine f2pyinithndrun(setupfunc)
      external setupfunc
      double precision runtes
      double precision eftes
      common /hndrun/ runtes,eftes
      call setupfunc(runtes,eftes)
      end

      subroutine f2pyinithnaddh(setupfunc)
      external setupfunc
      double precision amz(16)
      double precision gaz(16)
      double precision tauz(16)
      integer ichz(16)
      integer ibarz(16)
      integer k1z(16)
      integer k2z(16)
      double precision wtz(153)
      integer ii22
      integer nzk1(153)
      integer nzk2(153)
      integer nzk3(153)
      common /hnaddh/ amz,gaz,tauz,ichz,ibarz,k1z,k2z,wtz,ii22,nzk
     &1,nzk2,nzk3
      call setupfunc(amz,gaz,tauz,ichz,ibarz,k1z,k2z,wtz,ii22,nzk1
     &,nzk2,nzk3)
      end

      subroutine f2pyinithnaddn(setupfunc)
      external setupfunc
      character anamz(16,8)
      character zknam4(9,8)
      character zknam5(90,8)
      character zknam6(54,8)
      common /hnaddn/ anamz,zknam4,zknam5,zknam6
      call setupfunc(anamz,zknam4,zknam5,zknam6)
      end

      subroutine f2pyinitpoinou(setupfunc)
      external setupfunc
      integer li
      integer lo
      integer lpri
      integer lendir
      character*1024 datdir
      common /poinou/ li,lo,lpri,lendir,datdir
      call setupfunc(li,lo,lpri,lendir,datdir)
      end

      subroutine f2pyinitpodebg(setupfunc)
      external setupfunc
      integer ideb(100)
      integer kspom
      integer khpom
      integer ksreg
      integer khdir
      integer kaccep
      integer kstrg
      integer khtrg
      integer ksloo
      integer khloo
      integer ksdpo
      integer khdpo
      integer kevent
      integer ksoft
      integer khard
      common /podebg/ ideb,kspom,khpom,ksreg,khdir,kaccep,kstrg,kh
     &trg,ksloo,khloo,ksdpo,khdpo,kevent,ksoft,khard
      call setupfunc(ideb,kspom,khpom,ksreg,khdir,kaccep,kstrg,kht
     &rg,ksloo,khloo,ksdpo,khdpo,kevent,ksoft,khard)
      end

      subroutine f2pyinitpopar1(setupfunc)
      external setupfunc
      integer id_pdg_list(300)
      integer id_list(577)
      character name_list(300,12)
      integer id_pdg_max
      common /popar1/ id_pdg_list,id_list,name_list,id_pdg_max
      call setupfunc(id_pdg_list,id_list,name_list,id_pdg_max)
      end

      subroutine f2pyinitpocons(setupfunc)
      external setupfunc
      double precision pi
      double precision pi2
      double precision pi4
      double precision gev2mb
      double precision q_ch(13)
      double precision q_ch2(13)
      double precision q_ch4(13)
      common /pocons/ pi,pi2,pi4,gev2mb,q_ch,q_ch2,q_ch4
      call setupfunc(pi,pi2,pi4,gev2mb,q_ch,q_ch2,q_ch4)
      end

      subroutine f2pyinitpobeam(setupfunc)
      external setupfunc
      integer mparconf(2,40)
      integer mpmapp(2,40)
      integer mpar(2)
      double precision sqsglobmax
      integer nmpar
      integer idxmpar
      integer nmapp
      common /pobeam/ mparconf,mpmapp,mpar,sqsglobmax,nmpar,idxmpa
     &r,nmapp
      call setupfunc(mparconf,mpmapp,mpar,sqsglobmax,nmpar,idxmpar
     &,nmapp)
      end

      subroutine f2pyinitpomdls(setupfunc)
      external setupfunc
      character mdlna(50,8)
      integer iswmdl(50)
      double precision parmdl(400)
      integer ipamdl(400)
      character*1024 parfn
      common /pomdls/ mdlna,iswmdl,parmdl,ipamdl,parfn
      call setupfunc(mdlna,iswmdl,parmdl,ipamdl,parfn)
      end

      subroutine f2pyinitpohpro(setupfunc)
      external setupfunc
      character proc(17,18)
      common /pohpro/ proc
      call setupfunc(proc)
      end

      subroutine f2pyinitpohrcs(setupfunc)
      external setupfunc
      double precision hfac(18,40)
      double precision hwgx(18,40)
      double precision hsig(18,40)
      double precision hdpt(18,40)
      double precision hecm_last
      double precision hq2a_last
      double precision hq2b_last
      integer iha_last
      integer ihb_last
      integer mh_pro_on(18,5,40)
      integer mh_tried(18,5,40)
      integer mh_acc_1(18,5,40)
      integer mh_acc_2(18,5,40)
      common /pohrcs/ hfac,hwgx,hsig,hdpt,hecm_last,hq2a_last,hq2b
     &_last,iha_last,ihb_last,mh_pro_on,mh_tried,mh_acc_1,mh_acc_2
      call setupfunc(hfac,hwgx,hsig,hdpt,hecm_last,hq2a_last,hq2b_
     &last,iha_last,ihb_last,mh_pro_on,mh_tried,mh_acc_1,mh_acc_2)
      end

      subroutine f2pyinitpohtab(setupfunc)
      external setupfunc
      double precision hfac_tab(18,20,10,10,5,40)
      double precision hwgx_tab(18,20,10,10,5,40)
      double precision hsig_tab(18,20,10,10,5,40)
      double precision hdpt_tab(18,20,10,10,5,40)
      double precision hq2a_tab(10,5,40)
      double precision hq2b_tab(10,5,40)
      double precision hecm_tab(20,5,40)
      integer ih_q2a_up(5,40)
      integer ih_q2b_up(5,40)
      integer ih_ecm_up(5,40)
      common /pohtab/ hfac_tab,hwgx_tab,hsig_tab,hdpt_tab,hq2a_tab
     &,hq2b_tab,hecm_tab,ih_q2a_up,ih_q2b_up,ih_ecm_up
      call setupfunc(hfac_tab,hwgx_tab,hsig_tab,hdpt_tab,hq2a_tab,
     &hq2b_tab,hecm_tab,ih_q2a_up,ih_q2b_up,ih_ecm_up)
      end

      subroutine f2pyinitposbrn(setupfunc)
      external setupfunc
      complex*16 sigp
      complex*16 sigr
      complex*16 sighd
      complex*16 sighr
      complex*16 sigt1(2)
      complex*16 sigt2(2)
      complex*16 sigl
      complex*16 sigdp(4)
      complex*16 sigd1(2)
      complex*16 sigd2(2)
      complex*16 dsigh(17)
      common /posbrn/ sigp,sigr,sighd,sighr,sigt1,sigt2,sigl,sigdp
     &,sigd1,sigd2,dsigh
      call setupfunc(sigp,sigr,sighd,sighr,sigt1,sigt2,sigl,sigdp,
     &sigd1,sigd2,dsigh)
      end

      subroutine f2pyinitpozbrn(setupfunc)
      external setupfunc
      complex*16 zigp
      complex*16 zigr
      complex*16 zighd
      complex*16 zighr
      complex*16 zigt1(2)
      complex*16 zigt2(2)
      complex*16 zigl
      complex*16 zigdp(4)
      complex*16 zigd1(2)
      complex*16 zigd2(2)
      complex*16 bpom
      complex*16 breg
      complex*16 bhar
      complex*16 bhad
      complex*16 btr1(2)
      complex*16 btr2(2)
      complex*16 bloo
      complex*16 bdp(4)
      complex*16 bd1(2)
      complex*16 bd2(2)
      common /pozbrn/ zigp,zigr,zighd,zighr,zigt1,zigt2,zigl,zigdp
     &,zigd1,zigd2,bpom,breg,bhar,bhad,btr1,btr2,bloo,bdp,bd1,bd2
      call setupfunc(zigp,zigr,zighd,zighr,zigt1,zigt2,zigl,zigdp,
     &zigd1,zigd2,bpom,breg,bhar,bhad,btr1,btr2,bloo,bdp,bd1,bd2)
      end

      subroutine f2pyinitpopreg(setupfunc)
      external setupfunc
      double precision alpom
      double precision alpomp
      double precision gp(2)
      double precision b0pom(2)
      double precision alreg
      double precision alregp
      double precision gr(2)
      double precision b0reg(2)
      double precision gppp
      double precision gppr
      double precision b0ppp
      double precision b0ppr
      double precision vdmfac(4)
      double precision vdmq2f(4)
      double precision b0har
      double precision akfac
      common /popreg/ alpom,alpomp,gp,b0pom,alreg,alregp,gr,b0reg,
     &gppp,gppr,b0ppp,b0ppr,vdmfac,vdmq2f,b0har,akfac
      call setupfunc(alpom,alpomp,gp,b0pom,alreg,alregp,gr,b0reg,g
     &ppp,gppr,b0ppp,b0ppr,vdmfac,vdmq2f,b0har,akfac)
      end

      subroutine f2pyinitpo2cha(setupfunc)
      external setupfunc
      double precision phisup(2)
      double precision rmass(2)
      double precision var
      double precision ampfac(4)
      double precision elafac(4)
      double precision vfac
      common /po2cha/ phisup,rmass,var,ampfac,elafac,vfac
      call setupfunc(phisup,rmass,var,ampfac,elafac,vfac)
      end

      subroutine f2pyinitpopcms(setupfunc)
      external setupfunc
      double precision ecmp
      double precision pcmp
      double precision pmassp(2)
      double precision pvirtp(2)
      double precision gambep(4)
      double precision sidp
      double precision codp
      double precision sifp
      double precision cofp
      integer nposp(2)
      integer idpdg1
      integer idbam1
      integer idpdg2
      integer idbam2
      common /popcms/ ecmp,pcmp,pmassp,pvirtp,gambep,sidp,codp,sif
     &p,cofp,nposp,idpdg1,idbam1,idpdg2,idbam2
      call setupfunc(ecmp,pcmp,pmassp,pvirtp,gambep,sidp,codp,sifp
     &,cofp,nposp,idpdg1,idbam1,idpdg2,idbam2)
      end

      subroutine f2pyinitpocut1(setupfunc)
      external setupfunc
      double precision ptcut(4)
      double precision ptano(4)
      double precision fps(4)
      double precision fph(4)
      double precision psomin
      double precision xsomin
      common /pocut1/ ptcut,ptano,fps,fph,psomin,xsomin
      call setupfunc(ptcut,ptano,fps,fph,psomin,xsomin)
      end

      subroutine f2pyinitpoint3(setupfunc)
      external setupfunc
      double precision sigs
      double precision dsighp
      double precision sigh
      double precision fs
      double precision fh
      double precision betas(3)
      double precision aas
      double precision ptcon
      common /point3/ sigs,dsighp,sigh,fs,fh,betas,aas,ptcon
      call setupfunc(sigs,dsighp,sigh,fs,fh,betas,aas,ptcon)
      end

      subroutine f2pyinitpoprcs(setupfunc)
      external setupfunc
      integer iproce
      integer idnodf
      integer idifr1
      integer idifr2
      integer iddpom
      integer ipron(15,4)
      common /poprcs/ iproce,idnodf,idifr1,idifr2,iddpom,ipron
      call setupfunc(iproce,idnodf,idifr1,idifr2,iddpom,ipron)
      end

      subroutine f2pyinitpoloop(setupfunc)
      external setupfunc
      integer ifail(60)
      character rejtit(60,10)
      common /poloop/ ifail,rejtit
      call setupfunc(ifail,rejtit)
      end

      subroutine f2pyinitpofsrc(setupfunc)
      external setupfunc
      double precision pini(5,2)
      double precision pfin(5,2)
      double precision pgam(5,2)
      integer ighel(2)
      double precision gyy(2)
      double precision gq2(2)
      double precision ggecm
      double precision gaimp(2)
      double precision pfthe(2)
      double precision pfphi(2)
      integer idpsrc(2)
      integer idbsrc(2)
      double precision radsrc(2)
      double precision amsrc(2)
      double precision gamsrc(2)
      common /pofsrc/ pini,pfin,pgam,ighel,gyy,gq2,ggecm,gaimp,pft
     &he,pfphi,idpsrc,idbsrc,radsrc,amsrc,gamsrc
      call setupfunc(pini,pfin,pgam,ighel,gyy,gq2,ggecm,gaimp,pfth
     &e,pfphi,idpsrc,idbsrc,radsrc,amsrc,gamsrc)
      end

      subroutine f2pyinitpogcms(setupfunc)
      external setupfunc
      double precision ecm
      double precision pcm
      double precision pmass(2)
      double precision pvirt(2)
      integer ifpap(2)
      integer ifpab(2)
      common /pogcms/ ecm,pcm,pmass,pvirt,ifpap,ifpab
      call setupfunc(ecm,pcm,pmass,pvirt,ifpap,ifpab)
      end

      subroutine f2pyinitpocsec(setupfunc)
      external setupfunc
      double precision sigtot
      double precision sigela
      double precision sigvm(5,5)
      double precision sigine
      double precision signdf
      double precision sigdir
      double precision siglsd(2)
      double precision sighsd(2)
      double precision sigldd
      double precision sighdd
      double precision sigcdf(5)
      double precision sigpom
      double precision sigreg
      double precision sighar
      double precision sigtr1(2)
      double precision sigtr2(2)
      double precision sigloo
      double precision sigdpo(4)
      double precision sig1so
      double precision sig1ha
      double precision sloel
      double precision slovm(4,4)
      double precision sigcor
      double precision fsup(2)
      double precision fsud(2)
      double precision fsuh(2)
      double precision ecmfil
      double precision p2afil
      double precision p2bfil
      integer ipfil
      integer ifafil
      integer ifbfil
      common /pocsec/ sigtot,sigela,sigvm,sigine,signdf,sigdir,sig
     &lsd,sighsd,sigldd,sighdd,sigcdf,sigpom,sigreg,sighar,sigtr1,sigtr2
     &,sigloo,sigdpo,sig1so,sig1ha,sloel,slovm,sigcor,fsup,fsud,fsuh,ecm
     &fil,p2afil,p2bfil,ipfil,ifafil,ifbfil
      call setupfunc(sigtot,sigela,sigvm,sigine,signdf,sigdir,sigl
     &sd,sighsd,sigldd,sighdd,sigcdf,sigpom,sigreg,sighar,sigtr1,sigtr2,
     &sigloo,sigdpo,sig1so,sig1ha,sloel,slovm,sigcor,fsup,fsud,fsuh,ecmf
     &il,p2afil,p2bfil,ipfil,ifafil,ifbfil)
      end

      subroutine f2pyinitpowght(setupfunc)
      external setupfunc
      double precision siggen(4)
      double precision hswght(11)
      double precision hswcut(20)
      double precision evwght(11)
      integer ipowgc(11)
      integer iswcut(20)
      integer ivwght(11)
      common /powght/ siggen,hswght,hswcut,evwght,ipowgc,iswcut,iv
     &wght
      call setupfunc(siggen,hswght,hswcut,evwght,ipowgc,iswcut,ivw
     &ght)
      end

      subroutine f2pyinitporecu(setupfunc)
      external setupfunc
      integer ipopos(2,500)
      integer ipores(500)
      integer ipoix1
      integer ipoix2
      integer ipoix3
      common /porecu/ ipopos,ipores,ipoix1,ipoix2,ipoix3
      call setupfunc(ipopos,ipores,ipoix1,ipoix2,ipoix3)
      end

      subroutine f2pyinitpofcut(setupfunc)
      external setupfunc
      double precision ecmin
      double precision ecmax
      double precision eemin1
      double precision eemin2
      double precision ymin1
      double precision ymax1
      double precision ymin2
      double precision ymax2
      double precision q2min1
      double precision q2max1
      double precision q2min2
      double precision q2max2
      double precision thmin1
      double precision thmax1
      double precision thmin2
      double precision thmax2
      integer itag1
      integer itag2
      common /pofcut/ ecmin,ecmax,eemin1,eemin2,ymin1,ymax1,ymin2,
     &ymax2,q2min1,q2max1,q2min2,q2max2,thmin1,thmax1,thmin2,thmax2,itag
     &1,itag2
      call setupfunc(ecmin,ecmax,eemin1,eemin2,ymin1,ymax1,ymin2,y
     &max2,q2min1,q2max1,q2min2,q2max2,thmin1,thmax1,thmin2,thmax2,itag1
     &,itag2)
      end

      subroutine f2pyinitpohdfl(setupfunc)
      external setupfunc
      double precision ecmn
      double precision pcmn
      double precision secm
      double precision spcm
      double precision xpsub
      double precision xtsub
      integer ideqp(2)
      integer ideqb(2)
      integer ihfld(2,2)
      integer ihfls(2)
      common /pohdfl/ ecmn,pcmn,secm,spcm,xpsub,xtsub,ideqp,ideqb,
     &ihfld,ihfls
      call setupfunc(ecmn,pcmn,secm,spcm,xpsub,xtsub,ideqp,ideqb,i
     &hfld,ihfls)
      end

      subroutine f2pyinitpoevt1(setupfunc)
      external setupfunc
      integer nevhep
      integer nhep
      integer isthep(8000)
      integer idhep(8000)
      integer jmohep(2,8000)
      integer jdahep(2,8000)
      double precision phep(5,8000)
      double precision vhep(4,8000)
      common /poevt1/ nevhep,nhep,isthep,idhep,jmohep,jdahep,phep,
     &vhep
      call setupfunc(nevhep,nhep,isthep,idhep,jmohep,jdahep,phep,v
     &hep)
      end

      subroutine f2pyinitpoevt2(setupfunc)
      external setupfunc
      integer impart(8000)
      integer iphist(2,8000)
      integer icolor(2,8000)
      common /poevt2/ impart,iphist,icolor
      call setupfunc(impart,iphist,icolor)
      end

      subroutine f2pyinitpohscl(setupfunc)
      external setupfunc
      double precision aqqal
      double precision aqqali
      double precision aqqalf
      double precision aqqpd
      integer nqqal
      integer nqqali
      integer nqqalf
      integer nqqpd
      common /pohscl/ aqqal,aqqali,aqqalf,aqqpd,nqqal,nqqali,nqqal
     &f,nqqpd
      call setupfunc(aqqal,aqqali,aqqalf,aqqpd,nqqal,nqqali,nqqalf
     &,nqqpd)
      end

      subroutine f2pyinitpodgl1(setupfunc)
      external setupfunc
      double precision q2misr(2)
      double precision pmisr(2)
      double precision zmisr(2)
      double precision al2isr(2)
      integer nfsisr
      common /podgl1/ q2misr,pmisr,zmisr,al2isr,nfsisr
      call setupfunc(q2misr,pmisr,zmisr,al2isr,nfsisr)
      end

      subroutine f2pyinitpockin(setupfunc)
      external setupfunc
      double precision ptwant
      double precision as
      double precision ah
      double precision alns
      double precision alnh
      double precision z1max
      double precision z1dif
      double precision z2max
      double precision z2dif
      double precision pt
      double precision ptfin
      double precision etac
      double precision etad
      double precision x1
      double precision x2
      double precision v
      double precision u
      double precision w
      double precision w1
      double precision axx
      double precision qqpd
      double precision qqal
      double precision pdf1(13)
      double precision pdf2(13)
      double precision weight
      double precision phi1(5)
      double precision phi2(5)
      double precision pho1(5)
      double precision pho2(5)
      integer ia
      integer ib
      integer ic
      integer id
      integer iv1
      integer iv2
      integer mspr
      integer irejsc
      common /pockin/ ptwant,as,ah,alns,alnh,z1max,z1dif,z2max,z2d
     &if,pt,ptfin,etac,etad,x1,x2,v,u,w,w1,axx,qqpd,qqal,pdf1,pdf2,weigh
     &t,phi1,phi2,pho1,pho2,ia,ib,ic,id,iv1,iv2,mspr,irejsc
      call setupfunc(ptwant,as,ah,alns,alnh,z1max,z1dif,z2max,z2di
     &f,pt,ptfin,etac,etad,x1,x2,v,u,w,w1,axx,qqpd,qqal,pdf1,pdf2,weight
     &,phi1,phi2,pho1,pho2,ia,ib,ic,id,iv1,iv2,mspr,irejsc)
      end

      subroutine f2pyinitpotabl(setupfunc)
      external setupfunc
      double precision sigtab(80,20,4,40)
      double precision sigecm(20,4,40)
      double precision ecmf(4,40)
      integer isimax(40)
      common /potabl/ sigtab,sigecm,ecmf,isimax
      call setupfunc(sigtab,sigecm,ecmf,isimax)
      end

      subroutine f2pyinitpogaup(setupfunc)
      external setupfunc
      integer ngaup1
      integer ngaup2
      integer ngauet
      integer ngauin
      integer ngauso
      common /pogaup/ ngaup1,ngaup2,ngauet,ngauin,ngauso
      call setupfunc(ngaup1,ngaup2,ngauet,ngauin,ngauso)
      end

      subroutine f2pyinitpohapa(setupfunc)
      external setupfunc
      double precision alqcd2(3,4)
      double precision bqcd(4)
      integer nfbeta
      integer nf
      common /pohapa/ alqcd2,bqcd,nfbeta,nf
      call setupfunc(alqcd2,bqcd,nfbeta,nf)
      end

      subroutine f2pyinitpohdrn(setupfunc)
      external setupfunc
      double precision qmass(6)
      double precision bet
      double precision pcoudi
      double precision pnorm
      double precision valprg(2)
      integer nfs
      common /pohdrn/ qmass,bet,pcoudi,pnorm,valprg,nfs
      call setupfunc(qmass,bet,pcoudi,pnorm,valprg,nfs)
      end

      subroutine f2pyinitpoprob(setupfunc)
      external setupfunc
      double precision prob(20,21,501,4,40)
      double precision eptab(20,4,40)
      integer ieemax
      integer imax
      integer kmax
      common /poprob/ prob,eptab,ieemax,imax,kmax
      call setupfunc(prob,eptab,ieemax,imax,kmax)
      end

      subroutine f2pyinitpydat1(setupfunc)
      external setupfunc
      integer mstu(200)
      double precision paru(200)
      integer mstj(200)
      double precision parj(200)
      common /pydat1/ mstu,paru,mstj,parj
      call setupfunc(mstu,paru,mstj,parj)
      end

      subroutine f2pyinitpydat2(setupfunc)
      external setupfunc
      integer kchg(500,4)
      double precision pmas(500,4)
      double precision parf(2000)
      double precision vckm(4,4)
      common /pydat2/ kchg,pmas,parf,vckm
      call setupfunc(kchg,pmas,parf,vckm)
      end

      subroutine f2pyinitpydat3(setupfunc)
      external setupfunc
      integer mdcy(500,3)
      integer mdme(8000,2)
      double precision brat(8000)
      integer kfdp(8000,5)
      common /pydat3/ mdcy,mdme,brat,kfdp
      call setupfunc(mdcy,mdme,brat,kfdp)
      end

      subroutine f2pyinitpopar2(setupfunc)
      external setupfunc
      double precision xm_list(300)
      double precision tau_list(300)
      double precision gam_list(300)
      double precision xm_psm2_list(6,6)
      double precision xm_vem2_list(6,6)
      double precision xm_b82_list(6,6,6)
      double precision xm_b102_list(6,6,6)
      double precision xm_bb82_list(6,6,6,6)
      double precision xm_bb102_list(6,6,6,6)
      integer ich3_list(300)
      integer iba3_list(300)
      integer iq_list(3,300)
      integer id_psm_list(6,6)
      integer id_vem_list(6,6)
      integer id_b8_list(6,6,6)
      integer id_b10_list(6,6,6)
      common /popar2/ xm_list,tau_list,gam_list,xm_psm2_list,xm_ve
     &m2_list,xm_b82_list,xm_b102_list,xm_bb82_list,xm_bb102_list,ich3_l
     &ist,iba3_list,iq_list,id_psm_list,id_vem_list,id_b8_list,id_b10_li
     &st
      call setupfunc(xm_list,tau_list,gam_list,xm_psm2_list,xm_vem
     &2_list,xm_b82_list,xm_b102_list,xm_bb82_list,xm_bb102_list,ich3_li
     &st,iba3_list,iq_list,id_psm_list,id_vem_list,id_b8_list,id_b10_lis
     &t)
      end

      subroutine f2pyinitpospre(setupfunc)
      external setupfunc
      double precision salpom(40)
      double precision salpomp(40)
      double precision sgp(2,40)
      double precision sb0pom(2,40)
      double precision salreg(40)
      double precision salregp(40)
      double precision sgr(2,40)
      double precision sb0reg(2,40)
      double precision sgppp(40)
      double precision sgppr(40)
      double precision sb0ppp(40)
      double precision sb0ppr(40)
      double precision svdmfac(4,40)
      double precision svdmq2f(4,40)
      double precision sb0har(40)
      double precision sakfac(40)
      double precision sphisup(2,40)
      double precision srmass(2,40)
      common /pospre/ salpom,salpomp,sgp,sb0pom,salreg,salregp,sgr
     &,sb0reg,sgppp,sgppr,sb0ppp,sb0ppr,svdmfac,svdmq2f,sb0har,sakfac,sp
     &hisup,srmass
      call setupfunc(salpom,salpomp,sgp,sb0pom,salreg,salregp,sgr,
     &sb0reg,sgppp,sgppr,sb0ppp,sb0ppr,svdmfac,svdmq2f,sb0har,sakfac,sph
     &isup,srmass)
      end

      subroutine f2pyinitpopar3(setupfunc)
      external setupfunc
      double precision wg_sec_list(500)
      integer idec_list(3,300)
      integer isec_list(3,500)
      common /popar3/ wg_sec_list,idec_list,isec_list
      call setupfunc(wg_sec_list,idec_list,isec_list)
      end

      subroutine f2pyinitpoint4(setupfunc)
      external setupfunc
      complex*16 ampel
      complex*16 ampvm(4,4)
      complex*16 ampsof
      complex*16 amphar
      complex*16 amlmsd(2)
      complex*16 amhmsd(2)
      complex*16 amlmdd
      complex*16 amhmdd
      complex*16 ampdp(4)
      common /point4/ ampel,ampvm,ampsof,amphar,amlmsd,amhmsd,amlm
     &dd,amhmdd,ampdp
      call setupfunc(ampel,ampvm,ampsof,amphar,amlmsd,amhmsd,amlmd
     &d,amhmdd,ampdp)
      end

      subroutine f2pyinitpydat4(setupfunc)
      external setupfunc
      character chaf(500,2,16)
      common /pydat4/ chaf
      call setupfunc(chaf)
      end

      subroutine f2pyinitpydatr(setupfunc)
      external setupfunc
      integer mrpy(6)
      double precision rrpy(100)
      common /pydatr/ mrpy,rrpy
      call setupfunc(mrpy,rrpy)
      end

      subroutine f2pyinitpysubs(setupfunc)
      external setupfunc
      integer msel
      integer mselpd
      integer msub(500)
      integer kfin(2,81)
      double precision ckin(200)
      common /pysubs/ msel,mselpd,msub,kfin,ckin
      call setupfunc(msel,mselpd,msub,kfin,ckin)
      end

      subroutine f2pyinitpypars(setupfunc)
      external setupfunc
      integer mstp(200)
      double precision parp(200)
      integer msti(200)
      double precision pari(200)
      common /pypars/ mstp,parp,msti,pari
      call setupfunc(mstp,parp,msti,pari)
      end

      subroutine f2pyinitpyint1(setupfunc)
      external setupfunc
      integer mint(400)
      double precision vint(400)
      common /pyint1/ mint,vint
      call setupfunc(mint,vint)
      end

      subroutine f2pyinitpyint2(setupfunc)
      external setupfunc
      integer iset(500)
      integer kfpr(500,2)
      double precision coef(500,20)
      integer icol(40,4,2)
      common /pyint2/ iset,kfpr,coef,icol
      call setupfunc(iset,kfpr,coef,icol)
      end

      subroutine f2pyinitpyint3(setupfunc)
      external setupfunc
      double precision xsfx(2,81)
      integer isig(1000,3)
      double precision sigh(1000)
      common /pyint3/ xsfx,isig,sigh
      call setupfunc(xsfx,isig,sigh)
      end

      subroutine f2pyinitpyint4(setupfunc)
      external setupfunc
      integer mwid(500)
      double precision wids(500,5)
      common /pyint4/ mwid,wids
      call setupfunc(mwid,wids)
      end

      subroutine f2pyinitpyint5(setupfunc)
      external setupfunc
      integer ngenpd
      integer ngen(501,3)
      double precision xsec(501,3)
      common /pyint5/ ngenpd,ngen,xsec
      call setupfunc(ngenpd,ngen,xsec)
      end

      subroutine f2pyinitpyint6(setupfunc)
      external setupfunc
      character proc(501,28)
      common /pyint6/ proc
      call setupfunc(proc)
      end

      subroutine f2pyinitpyint7(setupfunc)
      external setupfunc
      double precision sigt(7,7,6)
      common /pyint7/ sigt
      call setupfunc(sigt)
      end

      subroutine f2pyinitpymssm(setupfunc)
      external setupfunc
      integer imss(100)
      double precision rmss(100)
      common /pymssm/ imss,rmss
      call setupfunc(imss,rmss)
      end

      subroutine f2pyinitpyssmt(setupfunc)
      external setupfunc
      double precision zmix(4,4)
      double precision umix(2,2)
      double precision vmix(2,2)
      double precision smz(4)
      double precision smw(2)
      double precision sfmix(16,4)
      double precision zmixi(4,4)
      double precision umixi(2,2)
      double precision vmixi(2,2)
      common /pyssmt/ zmix,umix,vmix,smz,smw,sfmix,zmixi,umixi,vmi
     &xi
      call setupfunc(zmix,umix,vmix,smz,smw,sfmix,zmixi,umixi,vmix
     &i)
      end

      subroutine f2pyinitpymsrv(setupfunc)
      external setupfunc
      double precision rvlam(3,3,3)
      double precision rvlamp(3,3,3)
      double precision rvlamb(3,3,3)
      common /pymsrv/ rvlam,rvlamp,rvlamb
      call setupfunc(rvlam,rvlamp,rvlamb)
      end

      subroutine f2pyinitpytcsm(setupfunc)
      external setupfunc
      integer itcm(100)
      double precision rtcm(100)
      common /pytcsm/ itcm,rtcm
      call setupfunc(itcm,rtcm)
      end

      subroutine f2pyinitpypued(setupfunc)
      external setupfunc
      integer iued(100)
      double precision rued(100)
      common /pypued/ iued,rued
      call setupfunc(iued,rued)
      end

      subroutine f2pyinitpybins(setupfunc)
      external setupfunc
      integer ihist(4)
      integer indx(1000)
      double precision bin(20000)
      common /pybins/ ihist,indx,bin
      call setupfunc(ihist,indx,bin)
      end

      subroutine f2pyinitpylh3p(setupfunc)
      external setupfunc
      integer modsel(200)
      double precision parmin(100)
      double precision parext(200)
      double precision rmsoft(101)
      double precision au(3,3)
      double precision ad(3,3)
      double precision ae(3,3)
      common /pylh3p/ modsel,parmin,parext,rmsoft,au,ad,ae
      call setupfunc(modsel,parmin,parext,rmsoft,au,ad,ae)
      end

      subroutine f2pyinitpylh3c(setupfunc)
      external setupfunc
      character cpro(2,12)
      character cver(2,12)
      common /pylh3c/ cpro,cver
      call setupfunc(cpro,cver)
      end

      subroutine f2pyinitdtevt1(setupfunc)
      external setupfunc
      integer nhkk
      integer nevhkk
      integer isthkk(250000)
      integer idhkk(250000)
      integer jmohkk(2,250000)
      integer jdahkk(2,250000)
      double precision phkk(5,250000)
      double precision vhkk(4,250000)
      double precision whkk(4,250000)
      common /dtevt1/ nhkk,nevhkk,isthkk,idhkk,jmohkk,jdahkk,phkk,
     &vhkk,whkk
      call setupfunc(nhkk,nevhkk,isthkk,idhkk,jmohkk,jdahkk,phkk,v
     &hkk,whkk)
      end

      subroutine f2pyinitdtevt2(setupfunc)
      external setupfunc
      integer idres(250000)
      integer idxres(250000)
      integer nobam(250000)
      integer idbam(250000)
      integer idch(250000)
      integer npoint(10)
      integer ihist(2,250000)
      common /dtevt2/ idres,idxres,nobam,idbam,idch,npoint,ihist
      call setupfunc(idres,idxres,nobam,idbam,idch,npoint,ihist)
      end

      subroutine f2pyinitdtrejc(setupfunc)
      external setupfunc
      integer irpt
      integer irhha
      integer irres(2)
      integer lomres
      integer lobres
      integer irchki(2)
      integer irfrag
      integer ircron(3)
      integer irevt
      integer irexci(3)
      integer irdiff(2)
      integer irinc
      common /dtrejc/ irpt,irhha,irres,lomres,lobres,irchki,irfrag
     &,ircron,irevt,irexci,irdiff,irinc
      call setupfunc(irpt,irhha,irres,lomres,lobres,irchki,irfrag,
     &ircron,irevt,irexci,irdiff,irinc)
      end

      subroutine f2pyinitdtimpa(setupfunc)
      external setupfunc
      double precision bimin
      double precision bimax
      double precision xsfrac
      integer icentr
      common /dtimpa/ bimin,bimax,xsfrac,icentr
      call setupfunc(bimin,bimax,xsfrac,icentr)
      end

      subroutine f2pyinitdtrnu1(setupfunc)
      external setupfunc
      double precision pinipr(5)
      double precision pinita(5)
      double precision prclpr(5)
      double precision prclta(5)
      double precision trclpr(5)
      double precision trclta(5)
      logical lrclpr
      logical lrclta
      common /dtrnu1/ pinipr,pinita,prclpr,prclta,trclpr,trclta,lr
     &clpr,lrclta
      call setupfunc(pinipr,pinita,prclpr,prclta,trclpr,trclta,lrc
     &lpr,lrclta)
      end

      subroutine f2pyinitdtrnu2(setupfunc)
      external setupfunc
      double precision amrcl0(2)
      double precision eexc(2)
      double precision eexcfi(2)
      integer ntot(2)
      integer npro(2)
      integer nn(2)
      integer nh(2)
      integer nhpos(2)
      integer nq(2)
      integer ntotfi(2)
      integer nprofi(2)
      common /dtrnu2/ amrcl0,eexc,eexcfi,ntot,npro,nn,nh,nhpos,nq,
     &ntotfi,nprofi
      call setupfunc(amrcl0,eexc,eexcfi,ntot,npro,nn,nh,nhpos,nq,n
     &totfi,nprofi)
      end

      subroutine f2pyinitdtsta2(setupfunc)
      external setupfunc
      double precision excdpm(4)
      double precision exceva(2)
      integer nincge
      integer nincco(2,3)
      integer ninchr(2,2)
      integer nincwo(2)
      integer nincst(2,4)
      integer nincev(2)
      integer nresto(2)
      integer nrespr(2)
      integer nresnu(2)
      integer nresba(2)
      integer nrespb(2)
      integer nresch(2)
      integer nresev(4)
      integer neva(2,6)
      integer nevaga(2)
      integer nevaht(2)
      integer nevahy(2,2,240)
      integer nevafi(2,2)
      common /dtsta2/ excdpm,exceva,nincge,nincco,ninchr,nincwo,ni
     &ncst,nincev,nresto,nrespr,nresnu,nresba,nrespb,nresch,nresev,neva,
     &nevaga,nevaht,nevahy,nevafi
      call setupfunc(excdpm,exceva,nincge,nincco,ninchr,nincwo,nin
     &cst,nincev,nresto,nrespr,nresnu,nresba,nrespb,nresch,nresev,neva,n
     &evaga,nevaht,nevahy,nevafi)
      end

      subroutine f2pyinitgenstk(setupfunc)
      external setupfunc
      double precision cxr(60000)
      double precision cyr(60000)
      double precision czr(60000)
      double precision cxrpol(60000)
      double precision cyrpol(60000)
      double precision czrpol(60000)
      double precision tki(60000)
      double precision plr(60000)
      double precision wei(60000)
      double precision agesec(60000)
      double precision tv
      double precision tvcms
      double precision tvrecl
      double precision tvheav
      double precision tvbind
      integer kpart(60000)
      integer infext(60000)
      integer np0
      integer np
      common /genstk/ cxr,cyr,czr,cxrpol,cyrpol,czrpol,tki,plr,wei
     &,agesec,tv,tvcms,tvrecl,tvheav,tvbind,kpart,infext,np0,np
      call setupfunc(cxr,cyr,czr,cxrpol,cyrpol,czrpol,tki,plr,wei,
     &agesec,tv,tvcms,tvrecl,tvheav,tvbind,kpart,infext,np0,np)
      end

      subroutine f2pyinitresnuc(setupfunc)
      external setupfunc
      double precision amntar
      double precision ammtar
      double precision amnzm1
      double precision ammzm1
      double precision amnnm1
      double precision ammnm1
      double precision anow
      double precision znow
      double precision ancoll
      double precision zncoll
      double precision ammlft
      double precision amnlft
      double precision eres
      double precision ekres
      double precision amnres
      double precision ammres
      double precision ptres
      double precision pxres
      double precision pyres
      double precision pzres
      double precision ptres2
      double precision angres
      double precision anxres
      double precision anyres
      double precision anzres
      double precision tvestr
      double precision anestr
      double precision bhyres(4)
      integer ktarp
      integer ktarn
      integer igreyp
      integer igreyn
      integer ipdpm0
      integer ipdpm1
      integer ipreeh
      integer iprdeu
      integer iprtri
      integer ipr3he
      integer ipr4he
      integer icres
      integer ibres
      integer istres
      integer ismres
      integer ihyres
      integer ievapl
      integer ievaph
      integer ievpho
      integer ievneu
      integer ievpro
      integer ievdeu
      integer ievtri
      integer iev3he
      integer iev4he
      integer ideexg
      integer ibtar
      integer ichtar
      integer ibleft
      integer icleft
      integer ichbln
      integer icestr
      integer ibestr
      integer iother
      integer khyres(4)
      logical lrnfss
      logical lfragm
      logical lfkevt
      common /resnuc/ amntar,ammtar,amnzm1,ammzm1,amnnm1,ammnm1,an
     &ow,znow,ancoll,zncoll,ammlft,amnlft,eres,ekres,amnres,ammres,ptres
     &,pxres,pyres,pzres,ptres2,angres,anxres,anyres,anzres,tvestr,anest
     &r,bhyres,ktarp,ktarn,igreyp,igreyn,ipdpm0,ipdpm1,ipreeh,iprdeu,ipr
     &tri,ipr3he,ipr4he,icres,ibres,istres,ismres,ihyres,ievapl,ievaph,i
     &evpho,ievneu,ievpro,ievdeu,ievtri,iev3he,iev4he,ideexg,ibtar,ichta
     &r,ibleft,icleft,ichbln,icestr,ibestr,iother,khyres,lrnfss,lfragm,l
     &fkevt
      call setupfunc(amntar,ammtar,amnzm1,ammzm1,amnnm1,ammnm1,ano
     &w,znow,ancoll,zncoll,ammlft,amnlft,eres,ekres,amnres,ammres,ptres,
     &pxres,pyres,pzres,ptres2,angres,anxres,anyres,anzres,tvestr,anestr
     &,bhyres,ktarp,ktarn,igreyp,igreyn,ipdpm0,ipdpm1,ipreeh,iprdeu,iprt
     &ri,ipr3he,ipr4he,icres,ibres,istres,ismres,ihyres,ievapl,ievaph,ie
     &vpho,ievneu,ievpro,ievdeu,ievtri,iev3he,iev4he,ideexg,ibtar,ichtar
     &,ibleft,icleft,ichbln,icestr,ibestr,iother,khyres,lrnfss,lfragm,lf
     &kevt)
      end

      subroutine f2pyinitnucdat(setupfunc)
      external setupfunc
      double precision av0wel
      double precision apfrmx
      double precision aefrmx
      double precision aefrma
      double precision rdsnuc
      double precision v0well(2)
      double precision pfrmmx(2)
      double precision efrmmx(2)
      double precision efrmav(2)
      double precision amnucl(2)
      double precision amnusq(2)
      double precision ebndng(2)
      double precision veffnu(2)
      double precision eslope(2)
      double precision pkmnnu(2)
      double precision ekmnnu(2)
      double precision pkmxnu(2)
      double precision ekmxnu(2)
      double precision ekmnav(2)
      double precision ekinav(2)
      double precision exmnav(2)
      double precision ekupnu(2)
      double precision exmnnu(2)
      double precision exupnu(2)
      double precision erclav(2)
      double precision eswell(2)
      double precision fincup(2)
      double precision amrcav
      double precision amrcsq
      double precision ato1o3
      double precision zto1o3
      double precision frmrfc
      double precision elbnde(131)
      common /nucdat/ av0wel,apfrmx,aefrmx,aefrma,rdsnuc,v0well,pf
     &rmmx,efrmmx,efrmav,amnucl,amnusq,ebndng,veffnu,eslope,pkmnnu,ekmnn
     &u,pkmxnu,ekmxnu,ekmnav,ekinav,exmnav,ekupnu,exmnnu,exupnu,erclav,e
     &swell,fincup,amrcav,amrcsq,ato1o3,zto1o3,frmrfc,elbnde
      call setupfunc(av0wel,apfrmx,aefrmx,aefrma,rdsnuc,v0well,pfr
     &mmx,efrmmx,efrmav,amnucl,amnusq,ebndng,veffnu,eslope,pkmnnu,ekmnnu
     &,pkmxnu,ekmxnu,ekmnav,ekinav,exmnav,ekupnu,exmnnu,exupnu,erclav,es
     &well,fincup,amrcav,amrcsq,ato1o3,zto1o3,frmrfc,elbnde)
      end

      subroutine f2pyinitparevt(setupfunc)
      external setupfunc
      double precision dpower
      double precision fsprd0
      double precision fshpfn
      double precision rn1gsc
      double precision rn2gsc
      double precision rnswtc
      logical ldiffr(64)
      logical lpower
      logical linctv
      logical levprt
      logical lheavy
      logical ldeexg
      logical lgdhpr
      logical lpreex
      logical lhlfix
      logical lprfix
      logical lparwv
      logical lsngch
      logical lschdf
      logical lbmprq
      logical lhadri
      logical lnucri
      logical lpeanu
      logical levbme
      logical levrqm
      logical lphdrc
      logical latmss
      logical lismrs
      logical lchdcy
      logical lchdcr
      logical lmlccr
      logical lrvkin
      logical lvp2xx
      logical lv2xnw
      logical lnwv2x
      logical levfin
      common /parevt/ dpower,fsprd0,fshpfn,rn1gsc,rn2gsc,rnswtc,ld
     &iffr,lpower,linctv,levprt,lheavy,ldeexg,lgdhpr,lpreex,lhlfix,lprfi
     &x,lparwv,lsngch,lschdf,lbmprq,lhadri,lnucri,lpeanu,levbme,levrqm,l
     &phdrc,latmss,lismrs,lchdcy,lchdcr,lmlccr,lrvkin,lvp2xx,lv2xnw,lnwv
     &2x,levfin
      call setupfunc(dpower,fsprd0,fshpfn,rn1gsc,rn2gsc,rnswtc,ldi
     &ffr,lpower,linctv,levprt,lheavy,ldeexg,lgdhpr,lpreex,lhlfix,lprfix
     &,lparwv,lsngch,lschdf,lbmprq,lhadri,lnucri,lpeanu,levbme,levrqm,lp
     &hdrc,latmss,lismrs,lchdcy,lchdcr,lmlccr,lrvkin,lvp2xx,lv2xnw,lnwv2
     &x,levfin)
      end

      subroutine f2pyinitfheavy(setupfunc)
      external setupfunc
      double precision cxheav(100)
      double precision cyheav(100)
      double precision czheav(100)
      double precision tkheav(100)
      double precision pheavy(100)
      double precision wheavy(100)
      double precision agheav(100)
      double precision bhheav(4,40)
      double precision amheav(40)
      double precision amnhea(40)
      integer kheavy(100)
      integer infhea(100)
      integer icheav(40)
      integer ibheav(40)
      integer imheav(40)
      integer ihheav(40)
      integer khheav(4,40)
      integer npheav
      common /fheavy/ cxheav,cyheav,czheav,tkheav,pheavy,wheavy,ag
     &heav,bhheav,amheav,amnhea,kheavy,infhea,icheav,ibheav,imheav,ihhea
     &v,khheav,npheav
      call setupfunc(cxheav,cyheav,czheav,tkheav,pheavy,wheavy,agh
     &eav,bhheav,amheav,amnhea,kheavy,infhea,icheav,ibheav,imheav,ihheav
     &,khheav,npheav)
      end

      subroutine f2pyinitfheavc(setupfunc)
      external setupfunc
      character anheav(40,8)
      common /fheavc/ anheav
      call setupfunc(anheav)
      end

      subroutine f2pyinitdtevno(setupfunc)
      external setupfunc
      integer nevent
      integer icasca
      common /dtevno/ nevent,icasca
      call setupfunc(nevent,icasca)
      end

      subroutine f2pyinitnpy(setupfunc)
      external setupfunc
      integer*8 bitgen
      common /npy/ bitgen
      call setupfunc(bitgen)
      end


