C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrappychge (pychgef2pywrap, kf)
      external pychge
      integer kf
      integer pychgef2pywrap, pychge
      pychgef2pywrap = pychge(kf)
      end


      subroutine f2pywrappycomp (pycompf2pywrap, kf)
      external pycomp
      integer kf
      integer pycompf2pywrap, pycomp
      pycompf2pywrap = pycomp(kf)
      end


      subroutine f2pywrappyk (pykf2pywrap, i, j)
      external pyk
      integer i
      integer j
      integer pykf2pywrap, pyk
      pykf2pywrap = pyk(i, j)
      end


      subroutine f2pyinitpydat1(setupfunc)
      external setupfunc
      integer mstu(200)
      double precision paru(200)
      integer mstj(200)
      double precision parj(200)
      common /pydat1/ mstu,paru,mstj,parj
      call setupfunc(mstu,paru,mstj,parj)
      end

      subroutine f2pyinitpydat2(setupfunc)
      external setupfunc
      integer kchg(500,4)
      double precision pmas(500,4)
      double precision parf(2000)
      double precision vckm(4,4)
      common /pydat2/ kchg,pmas,parf,vckm
      call setupfunc(kchg,pmas,parf,vckm)
      end

      subroutine f2pyinitpydat3(setupfunc)
      external setupfunc
      integer mdcy(500,3)
      integer mdme(8000,2)
      double precision brat(8000)
      integer kfdp(8000,5)
      common /pydat3/ mdcy,mdme,brat,kfdp
      call setupfunc(mdcy,mdme,brat,kfdp)
      end

      subroutine f2pyinitpydat4(setupfunc)
      external setupfunc
      character chaf(500,2,16)
      common /pydat4/ chaf
      call setupfunc(chaf)
      end

      subroutine f2pyinitpydatr(setupfunc)
      external setupfunc
      integer mrpy(6)
      double precision rrpy(100)
      common /pydatr/ mrpy,rrpy
      call setupfunc(mrpy,rrpy)
      end

      subroutine f2pyinitpysubs(setupfunc)
      external setupfunc
      integer msel
      integer mselpd
      integer msub(500)
      integer kfin(2,81)
      double precision ckin(200)
      common /pysubs/ msel,mselpd,msub,kfin,ckin
      call setupfunc(msel,mselpd,msub,kfin,ckin)
      end

      subroutine f2pyinitpypars(setupfunc)
      external setupfunc
      integer mstp(200)
      double precision parp(200)
      integer msti(200)
      double precision pari(200)
      common /pypars/ mstp,parp,msti,pari
      call setupfunc(mstp,parp,msti,pari)
      end

      subroutine f2pyinitpyint1(setupfunc)
      external setupfunc
      integer mint(400)
      double precision vint(400)
      common /pyint1/ mint,vint
      call setupfunc(mint,vint)
      end

      subroutine f2pyinitpyint2(setupfunc)
      external setupfunc
      integer iset(500)
      integer kfpr(500,2)
      double precision coef(500,20)
      integer icol(40,4,2)
      common /pyint2/ iset,kfpr,coef,icol
      call setupfunc(iset,kfpr,coef,icol)
      end

      subroutine f2pyinitpyint3(setupfunc)
      external setupfunc
      double precision xsfx(2,81)
      integer isig(1000,3)
      double precision sigh(1000)
      common /pyint3/ xsfx,isig,sigh
      call setupfunc(xsfx,isig,sigh)
      end

      subroutine f2pyinitpyint4(setupfunc)
      external setupfunc
      integer mwid(500)
      double precision wids(500,5)
      common /pyint4/ mwid,wids
      call setupfunc(mwid,wids)
      end

      subroutine f2pyinitpyint5(setupfunc)
      external setupfunc
      integer ngenpd
      integer ngen(501,3)
      double precision xsec(501,3)
      common /pyint5/ ngenpd,ngen,xsec
      call setupfunc(ngenpd,ngen,xsec)
      end

      subroutine f2pyinitpyint6(setupfunc)
      external setupfunc
      character proc(501,28)
      common /pyint6/ proc
      call setupfunc(proc)
      end

      subroutine f2pyinitpyint7(setupfunc)
      external setupfunc
      double precision sigt(7,7,6)
      common /pyint7/ sigt
      call setupfunc(sigt)
      end

      subroutine f2pyinitpymssm(setupfunc)
      external setupfunc
      integer imss(100)
      double precision rmss(100)
      common /pymssm/ imss,rmss
      call setupfunc(imss,rmss)
      end

      subroutine f2pyinitpyssmt(setupfunc)
      external setupfunc
      double precision zmix(4,4)
      double precision umix(2,2)
      double precision vmix(2,2)
      double precision smz(4)
      double precision smw(2)
      double precision sfmix(16,4)
      double precision zmixi(4,4)
      double precision umixi(2,2)
      double precision vmixi(2,2)
      common /pyssmt/ zmix,umix,vmix,smz,smw,sfmix,zmixi,umixi,vmi
     &xi
      call setupfunc(zmix,umix,vmix,smz,smw,sfmix,zmixi,umixi,vmix
     &i)
      end

      subroutine f2pyinitpymsrv(setupfunc)
      external setupfunc
      double precision rvlam(3,3,3)
      double precision rvlamp(3,3,3)
      double precision rvlamb(3,3,3)
      common /pymsrv/ rvlam,rvlamp,rvlamb
      call setupfunc(rvlam,rvlamp,rvlamb)
      end

      subroutine f2pyinitpytcsm(setupfunc)
      external setupfunc
      integer itcm(100)
      double precision rtcm(100)
      common /pytcsm/ itcm,rtcm
      call setupfunc(itcm,rtcm)
      end

      subroutine f2pyinitpypued(setupfunc)
      external setupfunc
      integer iued(100)
      double precision rued(100)
      common /pypued/ iued,rued
      call setupfunc(iued,rued)
      end

      subroutine f2pyinitpybins(setupfunc)
      external setupfunc
      integer ihist(4)
      integer indx(1000)
      double precision bin(20000)
      common /pybins/ ihist,indx,bin
      call setupfunc(ihist,indx,bin)
      end

      subroutine f2pyinitpylh3p(setupfunc)
      external setupfunc
      integer modsel(200)
      double precision parmin(100)
      double precision parext(200)
      double precision rmsoft(101)
      double precision au(3,3)
      double precision ad(3,3)
      double precision ae(3,3)
      common /pylh3p/ modsel,parmin,parext,rmsoft,au,ad,ae
      call setupfunc(modsel,parmin,parext,rmsoft,au,ad,ae)
      end

      subroutine f2pyinitpylh3c(setupfunc)
      external setupfunc
      character cpro(2,12)
      character cver(2,12)
      common /pylh3c/ cpro,cver
      call setupfunc(cpro,cver)
      end

      subroutine f2pyinitpyjets(setupfunc)
      external setupfunc
      integer n
      integer npad
      integer k(4000,5)
      double precision p(4000,5)
      double precision v(4000,5)
      common /pyjets/ n,npad,k,p,v
      call setupfunc(n,npad,k,p,v)
      end

      subroutine f2pyinithepevt(setupfunc)
      external setupfunc
      integer nevhep
      integer nhep
      integer isthep(4000)
      integer idhep(4000)
      integer jmohep(2,4000)
      integer jdahep(2,4000)
      double precision phep(5,4000)
      double precision vhep(4,4000)
      common /hepevt/ nevhep,nhep,isthep,idhep,jmohep,jdahep,phep,
     &vhep
      call setupfunc(nevhep,nhep,isthep,idhep,jmohep,jdahep,phep,v
     &hep)
      end

      subroutine f2pyinitw50511(setupfunc)
      external setupfunc
      integer nptype
      integer ngroup
      integer nset
      integer mode
      integer nfl
      integer lo
      double precision tmas
      common /w50511/ nptype,ngroup,nset,mode,nfl,lo,tmas
      call setupfunc(nptype,ngroup,nset,mode,nfl,lo,tmas)
      end

      subroutine f2pyinitw50512(setupfunc)
      external setupfunc
      double precision qcdl4
      double precision qcdl5
      common /w50512/ qcdl4,qcdl5
      call setupfunc(qcdl4,qcdl5)
      end

      subroutine f2pyinitpypart(setupfunc)
      external setupfunc
      integer npart
      integer npartd
      integer ipart(1000)
      double precision ptpart(1000)
      common /pypart/ npart,npartd,ipart,ptpart
      call setupfunc(npart,npartd,ipart,ptpart)
      end

      subroutine f2pyinitpyctag(setupfunc)
      external setupfunc
      integer nct
      integer mct(4000,2)
      common /pyctag/ nct,mct
      call setupfunc(nct,mct)
      end

      subroutine f2pyinitpyintm(setupfunc)
      external setupfunc
      integer kfival(2,3)
      integer nmi(2)
      integer imi(2,800,2)
      integer nvc(2,13)
      double precision xassoc(2,13,240)
      double precision xpsvc(13,242)
      double precision pvctot(2,3)
      double precision xmi(2,240)
      double precision pt2mi(240)
      integer imisep(241)
      common /pyintm/ kfival,nmi,imi,nvc,xassoc,xpsvc,pvctot,xmi,p
     &t2mi,imisep
      call setupfunc(kfival,nmi,imi,nvc,xassoc,xpsvc,pvctot,xmi,pt
     &2mi,imisep)
      end

      subroutine f2pyinithepeup(setupfunc)
      external setupfunc
      integer nup
      integer idprup
      double precision xwgtup
      double precision scalup
      double precision aqedup
      double precision aqcdup
      integer idup(500)
      integer istup(500)
      integer mothup(2,500)
      integer icolup(2,500)
      double precision pup(5,500)
      double precision vtimup(500)
      double precision spinup(500)
      common /hepeup/ nup,idprup,xwgtup,scalup,aqedup,aqcdup,idup,
     &istup,mothup,icolup,pup,vtimup,spinup
      call setupfunc(nup,idprup,xwgtup,scalup,aqedup,aqcdup,idup,i
     &stup,mothup,icolup,pup,vtimup,spinup)
      end


