/* File: _pythia6module.c
 * This file is auto-generated with f2py (version:1.23.5).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Jan 16 05:26:03 2023
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_pythia6_error;
static PyObject *_pythia6_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*need_cfuncs*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_pydat1_def[] = {
  {"mstu",1,{{200}},NPY_INT},
  {"paru",1,{{200}},NPY_DOUBLE},
  {"mstj",1,{{200}},NPY_INT},
  {"parj",1,{{200}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pydat1(char *mstu,char *paru,char *mstj,char *parj) {
  int i_f2py=0;
  f2py_pydat1_def[i_f2py++].data = mstu;
  f2py_pydat1_def[i_f2py++].data = paru;
  f2py_pydat1_def[i_f2py++].data = mstj;
  f2py_pydat1_def[i_f2py++].data = parj;
}
extern void F_FUNC(f2pyinitpydat1,F2PYINITPYDAT1)(void(*)(char*,char*,char*,char*));
static void f2py_init_pydat1(void) {
  F_FUNC(f2pyinitpydat1,F2PYINITPYDAT1)(f2py_setup_pydat1);
}

static FortranDataDef f2py_pydat2_def[] = {
  {"kchg",2,{{500,4}},NPY_INT},
  {"pmas",2,{{500,4}},NPY_DOUBLE},
  {"parf",1,{{2000}},NPY_DOUBLE},
  {"vckm",2,{{4,4}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pydat2(char *kchg,char *pmas,char *parf,char *vckm) {
  int i_f2py=0;
  f2py_pydat2_def[i_f2py++].data = kchg;
  f2py_pydat2_def[i_f2py++].data = pmas;
  f2py_pydat2_def[i_f2py++].data = parf;
  f2py_pydat2_def[i_f2py++].data = vckm;
}
extern void F_FUNC(f2pyinitpydat2,F2PYINITPYDAT2)(void(*)(char*,char*,char*,char*));
static void f2py_init_pydat2(void) {
  F_FUNC(f2pyinitpydat2,F2PYINITPYDAT2)(f2py_setup_pydat2);
}

static FortranDataDef f2py_pydat3_def[] = {
  {"mdcy",2,{{500,3}},NPY_INT},
  {"mdme",2,{{8000,2}},NPY_INT},
  {"brat",1,{{8000}},NPY_DOUBLE},
  {"kfdp",2,{{8000,5}},NPY_INT},
  {NULL}
};
static void f2py_setup_pydat3(char *mdcy,char *mdme,char *brat,char *kfdp) {
  int i_f2py=0;
  f2py_pydat3_def[i_f2py++].data = mdcy;
  f2py_pydat3_def[i_f2py++].data = mdme;
  f2py_pydat3_def[i_f2py++].data = brat;
  f2py_pydat3_def[i_f2py++].data = kfdp;
}
extern void F_FUNC(f2pyinitpydat3,F2PYINITPYDAT3)(void(*)(char*,char*,char*,char*));
static void f2py_init_pydat3(void) {
  F_FUNC(f2pyinitpydat3,F2PYINITPYDAT3)(f2py_setup_pydat3);
}

static FortranDataDef f2py_pydat4_def[] = {
  {"chaf",3,{{500,2,16}},NPY_STRING},
  {NULL}
};
static void f2py_setup_pydat4(char *chaf) {
  int i_f2py=0;
  f2py_pydat4_def[i_f2py++].data = chaf;
}
extern void F_FUNC(f2pyinitpydat4,F2PYINITPYDAT4)(void(*)(char*));
static void f2py_init_pydat4(void) {
  F_FUNC(f2pyinitpydat4,F2PYINITPYDAT4)(f2py_setup_pydat4);
}

static FortranDataDef f2py_pydatr_def[] = {
  {"mrpy",1,{{6}},NPY_INT},
  {"rrpy",1,{{100}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pydatr(char *mrpy,char *rrpy) {
  int i_f2py=0;
  f2py_pydatr_def[i_f2py++].data = mrpy;
  f2py_pydatr_def[i_f2py++].data = rrpy;
}
extern void F_FUNC(f2pyinitpydatr,F2PYINITPYDATR)(void(*)(char*,char*));
static void f2py_init_pydatr(void) {
  F_FUNC(f2pyinitpydatr,F2PYINITPYDATR)(f2py_setup_pydatr);
}

static FortranDataDef f2py_pysubs_def[] = {
  {"msel",0,{{-1}},NPY_INT},
  {"mselpd",0,{{-1}},NPY_INT},
  {"msub",1,{{500}},NPY_INT},
  {"kfin",2,{{2,81}},NPY_INT},
  {"ckin",1,{{200}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pysubs(char *msel,char *mselpd,char *msub,char *kfin,char *ckin) {
  int i_f2py=0;
  f2py_pysubs_def[i_f2py++].data = msel;
  f2py_pysubs_def[i_f2py++].data = mselpd;
  f2py_pysubs_def[i_f2py++].data = msub;
  f2py_pysubs_def[i_f2py++].data = kfin;
  f2py_pysubs_def[i_f2py++].data = ckin;
}
extern void F_FUNC(f2pyinitpysubs,F2PYINITPYSUBS)(void(*)(char*,char*,char*,char*,char*));
static void f2py_init_pysubs(void) {
  F_FUNC(f2pyinitpysubs,F2PYINITPYSUBS)(f2py_setup_pysubs);
}

static FortranDataDef f2py_pypars_def[] = {
  {"mstp",1,{{200}},NPY_INT},
  {"parp",1,{{200}},NPY_DOUBLE},
  {"msti",1,{{200}},NPY_INT},
  {"pari",1,{{200}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pypars(char *mstp,char *parp,char *msti,char *pari) {
  int i_f2py=0;
  f2py_pypars_def[i_f2py++].data = mstp;
  f2py_pypars_def[i_f2py++].data = parp;
  f2py_pypars_def[i_f2py++].data = msti;
  f2py_pypars_def[i_f2py++].data = pari;
}
extern void F_FUNC(f2pyinitpypars,F2PYINITPYPARS)(void(*)(char*,char*,char*,char*));
static void f2py_init_pypars(void) {
  F_FUNC(f2pyinitpypars,F2PYINITPYPARS)(f2py_setup_pypars);
}

static FortranDataDef f2py_pyint1_def[] = {
  {"mint",1,{{400}},NPY_INT},
  {"vint",1,{{400}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pyint1(char *mint,char *vint) {
  int i_f2py=0;
  f2py_pyint1_def[i_f2py++].data = mint;
  f2py_pyint1_def[i_f2py++].data = vint;
}
extern void F_FUNC(f2pyinitpyint1,F2PYINITPYINT1)(void(*)(char*,char*));
static void f2py_init_pyint1(void) {
  F_FUNC(f2pyinitpyint1,F2PYINITPYINT1)(f2py_setup_pyint1);
}

static FortranDataDef f2py_pyint2_def[] = {
  {"iset",1,{{500}},NPY_INT},
  {"kfpr",2,{{500,2}},NPY_INT},
  {"coef",2,{{500,20}},NPY_DOUBLE},
  {"icol",3,{{40,4,2}},NPY_INT},
  {NULL}
};
static void f2py_setup_pyint2(char *iset,char *kfpr,char *coef,char *icol) {
  int i_f2py=0;
  f2py_pyint2_def[i_f2py++].data = iset;
  f2py_pyint2_def[i_f2py++].data = kfpr;
  f2py_pyint2_def[i_f2py++].data = coef;
  f2py_pyint2_def[i_f2py++].data = icol;
}
extern void F_FUNC(f2pyinitpyint2,F2PYINITPYINT2)(void(*)(char*,char*,char*,char*));
static void f2py_init_pyint2(void) {
  F_FUNC(f2pyinitpyint2,F2PYINITPYINT2)(f2py_setup_pyint2);
}

static FortranDataDef f2py_pyint3_def[] = {
  {"xsfx",2,{{2,81}},NPY_DOUBLE},
  {"isig",2,{{1000,3}},NPY_INT},
  {"sigh",1,{{1000}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pyint3(char *xsfx,char *isig,char *sigh) {
  int i_f2py=0;
  f2py_pyint3_def[i_f2py++].data = xsfx;
  f2py_pyint3_def[i_f2py++].data = isig;
  f2py_pyint3_def[i_f2py++].data = sigh;
}
extern void F_FUNC(f2pyinitpyint3,F2PYINITPYINT3)(void(*)(char*,char*,char*));
static void f2py_init_pyint3(void) {
  F_FUNC(f2pyinitpyint3,F2PYINITPYINT3)(f2py_setup_pyint3);
}

static FortranDataDef f2py_pyint4_def[] = {
  {"mwid",1,{{500}},NPY_INT},
  {"wids",2,{{500,5}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pyint4(char *mwid,char *wids) {
  int i_f2py=0;
  f2py_pyint4_def[i_f2py++].data = mwid;
  f2py_pyint4_def[i_f2py++].data = wids;
}
extern void F_FUNC(f2pyinitpyint4,F2PYINITPYINT4)(void(*)(char*,char*));
static void f2py_init_pyint4(void) {
  F_FUNC(f2pyinitpyint4,F2PYINITPYINT4)(f2py_setup_pyint4);
}

static FortranDataDef f2py_pyint5_def[] = {
  {"ngenpd",0,{{-1}},NPY_INT},
  {"ngen",2,{{501,3}},NPY_INT},
  {"xsec",2,{{501,3}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pyint5(char *ngenpd,char *ngen,char *xsec) {
  int i_f2py=0;
  f2py_pyint5_def[i_f2py++].data = ngenpd;
  f2py_pyint5_def[i_f2py++].data = ngen;
  f2py_pyint5_def[i_f2py++].data = xsec;
}
extern void F_FUNC(f2pyinitpyint5,F2PYINITPYINT5)(void(*)(char*,char*,char*));
static void f2py_init_pyint5(void) {
  F_FUNC(f2pyinitpyint5,F2PYINITPYINT5)(f2py_setup_pyint5);
}

static FortranDataDef f2py_pyint6_def[] = {
  {"proc",2,{{501,28}},NPY_STRING},
  {NULL}
};
static void f2py_setup_pyint6(char *proc) {
  int i_f2py=0;
  f2py_pyint6_def[i_f2py++].data = proc;
}
extern void F_FUNC(f2pyinitpyint6,F2PYINITPYINT6)(void(*)(char*));
static void f2py_init_pyint6(void) {
  F_FUNC(f2pyinitpyint6,F2PYINITPYINT6)(f2py_setup_pyint6);
}

static FortranDataDef f2py_pyint7_def[] = {
  {"sigt",3,{{7,7,6}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pyint7(char *sigt) {
  int i_f2py=0;
  f2py_pyint7_def[i_f2py++].data = sigt;
}
extern void F_FUNC(f2pyinitpyint7,F2PYINITPYINT7)(void(*)(char*));
static void f2py_init_pyint7(void) {
  F_FUNC(f2pyinitpyint7,F2PYINITPYINT7)(f2py_setup_pyint7);
}

static FortranDataDef f2py_pymssm_def[] = {
  {"imss",1,{{100}},NPY_INT},
  {"rmss",1,{{100}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pymssm(char *imss,char *rmss) {
  int i_f2py=0;
  f2py_pymssm_def[i_f2py++].data = imss;
  f2py_pymssm_def[i_f2py++].data = rmss;
}
extern void F_FUNC(f2pyinitpymssm,F2PYINITPYMSSM)(void(*)(char*,char*));
static void f2py_init_pymssm(void) {
  F_FUNC(f2pyinitpymssm,F2PYINITPYMSSM)(f2py_setup_pymssm);
}

static FortranDataDef f2py_pyssmt_def[] = {
  {"zmix",2,{{4,4}},NPY_DOUBLE},
  {"umix",2,{{2,2}},NPY_DOUBLE},
  {"vmix",2,{{2,2}},NPY_DOUBLE},
  {"smz",1,{{4}},NPY_DOUBLE},
  {"smw",1,{{2}},NPY_DOUBLE},
  {"sfmix",2,{{16,4}},NPY_DOUBLE},
  {"zmixi",2,{{4,4}},NPY_DOUBLE},
  {"umixi",2,{{2,2}},NPY_DOUBLE},
  {"vmixi",2,{{2,2}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pyssmt(char *zmix,char *umix,char *vmix,char *smz,char *smw,char *sfmix,char *zmixi,char *umixi,char *vmixi) {
  int i_f2py=0;
  f2py_pyssmt_def[i_f2py++].data = zmix;
  f2py_pyssmt_def[i_f2py++].data = umix;
  f2py_pyssmt_def[i_f2py++].data = vmix;
  f2py_pyssmt_def[i_f2py++].data = smz;
  f2py_pyssmt_def[i_f2py++].data = smw;
  f2py_pyssmt_def[i_f2py++].data = sfmix;
  f2py_pyssmt_def[i_f2py++].data = zmixi;
  f2py_pyssmt_def[i_f2py++].data = umixi;
  f2py_pyssmt_def[i_f2py++].data = vmixi;
}
extern void F_FUNC(f2pyinitpyssmt,F2PYINITPYSSMT)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_pyssmt(void) {
  F_FUNC(f2pyinitpyssmt,F2PYINITPYSSMT)(f2py_setup_pyssmt);
}

static FortranDataDef f2py_pymsrv_def[] = {
  {"rvlam",3,{{3,3,3}},NPY_DOUBLE},
  {"rvlamp",3,{{3,3,3}},NPY_DOUBLE},
  {"rvlamb",3,{{3,3,3}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pymsrv(char *rvlam,char *rvlamp,char *rvlamb) {
  int i_f2py=0;
  f2py_pymsrv_def[i_f2py++].data = rvlam;
  f2py_pymsrv_def[i_f2py++].data = rvlamp;
  f2py_pymsrv_def[i_f2py++].data = rvlamb;
}
extern void F_FUNC(f2pyinitpymsrv,F2PYINITPYMSRV)(void(*)(char*,char*,char*));
static void f2py_init_pymsrv(void) {
  F_FUNC(f2pyinitpymsrv,F2PYINITPYMSRV)(f2py_setup_pymsrv);
}

static FortranDataDef f2py_pytcsm_def[] = {
  {"itcm",1,{{100}},NPY_INT},
  {"rtcm",1,{{100}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pytcsm(char *itcm,char *rtcm) {
  int i_f2py=0;
  f2py_pytcsm_def[i_f2py++].data = itcm;
  f2py_pytcsm_def[i_f2py++].data = rtcm;
}
extern void F_FUNC(f2pyinitpytcsm,F2PYINITPYTCSM)(void(*)(char*,char*));
static void f2py_init_pytcsm(void) {
  F_FUNC(f2pyinitpytcsm,F2PYINITPYTCSM)(f2py_setup_pytcsm);
}

static FortranDataDef f2py_pypued_def[] = {
  {"iued",1,{{100}},NPY_INT},
  {"rued",1,{{100}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pypued(char *iued,char *rued) {
  int i_f2py=0;
  f2py_pypued_def[i_f2py++].data = iued;
  f2py_pypued_def[i_f2py++].data = rued;
}
extern void F_FUNC(f2pyinitpypued,F2PYINITPYPUED)(void(*)(char*,char*));
static void f2py_init_pypued(void) {
  F_FUNC(f2pyinitpypued,F2PYINITPYPUED)(f2py_setup_pypued);
}

static FortranDataDef f2py_pybins_def[] = {
  {"ihist",1,{{4}},NPY_INT},
  {"indx",1,{{1000}},NPY_INT},
  {"bin",1,{{20000}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pybins(char *ihist,char *indx,char *bin) {
  int i_f2py=0;
  f2py_pybins_def[i_f2py++].data = ihist;
  f2py_pybins_def[i_f2py++].data = indx;
  f2py_pybins_def[i_f2py++].data = bin;
}
extern void F_FUNC(f2pyinitpybins,F2PYINITPYBINS)(void(*)(char*,char*,char*));
static void f2py_init_pybins(void) {
  F_FUNC(f2pyinitpybins,F2PYINITPYBINS)(f2py_setup_pybins);
}

static FortranDataDef f2py_pylh3p_def[] = {
  {"modsel",1,{{200}},NPY_INT},
  {"parmin",1,{{100}},NPY_DOUBLE},
  {"parext",1,{{200}},NPY_DOUBLE},
  {"rmsoft",1,{{101}},NPY_DOUBLE},
  {"au",2,{{3,3}},NPY_DOUBLE},
  {"ad",2,{{3,3}},NPY_DOUBLE},
  {"ae",2,{{3,3}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_pylh3p(char *modsel,char *parmin,char *parext,char *rmsoft,char *au,char *ad,char *ae) {
  int i_f2py=0;
  f2py_pylh3p_def[i_f2py++].data = modsel;
  f2py_pylh3p_def[i_f2py++].data = parmin;
  f2py_pylh3p_def[i_f2py++].data = parext;
  f2py_pylh3p_def[i_f2py++].data = rmsoft;
  f2py_pylh3p_def[i_f2py++].data = au;
  f2py_pylh3p_def[i_f2py++].data = ad;
  f2py_pylh3p_def[i_f2py++].data = ae;
}
extern void F_FUNC(f2pyinitpylh3p,F2PYINITPYLH3P)(void(*)(char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_pylh3p(void) {
  F_FUNC(f2pyinitpylh3p,F2PYINITPYLH3P)(f2py_setup_pylh3p);
}

static FortranDataDef f2py_pylh3c_def[] = {
  {"cpro",2,{{2,12}},NPY_STRING},
  {"cver",2,{{2,12}},NPY_STRING},
  {NULL}
};
static void f2py_setup_pylh3c(char *cpro,char *cver) {
  int i_f2py=0;
  f2py_pylh3c_def[i_f2py++].data = cpro;
  f2py_pylh3c_def[i_f2py++].data = cver;
}
extern void F_FUNC(f2pyinitpylh3c,F2PYINITPYLH3C)(void(*)(char*,char*));
static void f2py_init_pylh3c(void) {
  F_FUNC(f2pyinitpylh3c,F2PYINITPYLH3C)(f2py_setup_pylh3c);
}
/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_pythia6",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__pythia6(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _pythia6_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _pythia6 (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.23.5");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_pythia6' is auto-generated with f2py (version:1.23.5).\nFunctions:\n"
"COMMON blocks:\n""  /pydat1/ mstu(200),paru(200),mstj(200),parj(200)\n""  /pydat2/ kchg(500,4),pmas(500,4),parf(2000),vckm(4,4)\n""  /pydat3/ mdcy(500,3),mdme(8000,2),brat(8000),kfdp(8000,5)\n""  /pydat4/ chaf(500,2,16)\n""  /pydatr/ mrpy(6),rrpy(100)\n""  /pysubs/ msel,mselpd,msub(500),kfin(2,81),ckin(200)\n""  /pypars/ mstp(200),parp(200),msti(200),pari(200)\n""  /pyint1/ mint(400),vint(400)\n""  /pyint2/ iset(500),kfpr(500,2),coef(500,20),icol(40,4,2)\n""  /pyint3/ xsfx(2,81),isig(1000,3),sigh(1000)\n""  /pyint4/ mwid(500),wids(500,5)\n""  /pyint5/ ngenpd,ngen(501,3),xsec(501,3)\n""  /pyint6/ proc(501,28)\n""  /pyint7/ sigt(7,7,6)\n""  /pymssm/ imss(100),rmss(100)\n""  /pyssmt/ zmix(4,4),umix(2,2),vmix(2,2),smz(4),smw(2),sfmix(16,4),zmixi(4,4),umixi(2,2),vmixi(2,2)\n""  /pymsrv/ rvlam(3,3,3),rvlamp(3,3,3),rvlamb(3,3,3)\n""  /pytcsm/ itcm(100),rtcm(100)\n""  /pypued/ iued(100),rued(100)\n""  /pybins/ ihist(4),indx(1000),bin(20000)\n""  /pylh3p/ modsel(200),parmin(100),parext(200),rmsoft(101),au(3,3),ad(3,3),ae(3,3)\n""  /pylh3c/ cpro(2,12),cver(2,12)\n"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.23.5");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _pythia6_error = PyErr_NewException ("_pythia6.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__pythia6_error", _pythia6_error);
    Py_DECREF(_pythia6_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  tmp = PyFortranObject_New(f2py_pydat1_def,f2py_init_pydat1);
  F2PyDict_SetItemString(d, "pydat1", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pydat2_def,f2py_init_pydat2);
  F2PyDict_SetItemString(d, "pydat2", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pydat3_def,f2py_init_pydat3);
  F2PyDict_SetItemString(d, "pydat3", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pydat4_def,f2py_init_pydat4);
  F2PyDict_SetItemString(d, "pydat4", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pydatr_def,f2py_init_pydatr);
  F2PyDict_SetItemString(d, "pydatr", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pysubs_def,f2py_init_pysubs);
  F2PyDict_SetItemString(d, "pysubs", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pypars_def,f2py_init_pypars);
  F2PyDict_SetItemString(d, "pypars", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pyint1_def,f2py_init_pyint1);
  F2PyDict_SetItemString(d, "pyint1", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pyint2_def,f2py_init_pyint2);
  F2PyDict_SetItemString(d, "pyint2", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pyint3_def,f2py_init_pyint3);
  F2PyDict_SetItemString(d, "pyint3", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pyint4_def,f2py_init_pyint4);
  F2PyDict_SetItemString(d, "pyint4", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pyint5_def,f2py_init_pyint5);
  F2PyDict_SetItemString(d, "pyint5", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pyint6_def,f2py_init_pyint6);
  F2PyDict_SetItemString(d, "pyint6", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pyint7_def,f2py_init_pyint7);
  F2PyDict_SetItemString(d, "pyint7", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pymssm_def,f2py_init_pymssm);
  F2PyDict_SetItemString(d, "pymssm", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pyssmt_def,f2py_init_pyssmt);
  F2PyDict_SetItemString(d, "pyssmt", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pymsrv_def,f2py_init_pymsrv);
  F2PyDict_SetItemString(d, "pymsrv", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pytcsm_def,f2py_init_pytcsm);
  F2PyDict_SetItemString(d, "pytcsm", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pypued_def,f2py_init_pypued);
  F2PyDict_SetItemString(d, "pypued", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pybins_def,f2py_init_pybins);
  F2PyDict_SetItemString(d, "pybins", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pylh3p_def,f2py_init_pylh3p);
  F2PyDict_SetItemString(d, "pylh3p", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_pylh3c_def,f2py_init_pylh3c);
  F2PyDict_SetItemString(d, "pylh3c", tmp);
  Py_DECREF(tmp);/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_pythia6");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
