C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapqgsect (qgsectf2pywrap, e0n, icz, iap0, i
     &at0)
      external qgsect
      double precision e0n
      integer icz
      integer iap0
      integer iat0
      double precision qgsectf2pywrap, qgsect
      qgsectf2pywrap = qgsect(e0n, icz, iap0, iat0)
      end


      subroutine f2pyinitqgarr1(setupfunc)
      external setupfunc
      integer ia(2)
      integer icz
      integer icp
      common /qgarr1/ ia,icz,icp
      call setupfunc(ia,icz,icp)
      end

      subroutine f2pyinitqgarr2(setupfunc)
      external setupfunc
      double precision scm
      double precision wp0
      double precision wm0
      common /qgarr2/ scm,wp0,wm0
      call setupfunc(scm,wp0,wm0)
      end

      subroutine f2pyinitqgarr4(setupfunc)
      external setupfunc
      double precision ey0(3)
      common /qgarr4/ ey0
      call setupfunc(ey0)
      end

      subroutine f2pyinitqgarr5(setupfunc)
      external setupfunc
      double precision rnuc(2)
      double precision wsnuc(2)
      double precision wbnuc(2)
      double precision anorm
      double precision cr1(2)
      double precision cr2(2)
      double precision cr3(2)
      common /qgarr5/ rnuc,wsnuc,wbnuc,anorm,cr1,cr2,cr3
      call setupfunc(rnuc,wsnuc,wbnuc,anorm,cr1,cr2,cr3)
      end

      subroutine f2pyinitqgarr6(setupfunc)
      external setupfunc
      double precision pi
      double precision bm
      double precision amws
      common /qgarr6/ pi,bm,amws
      call setupfunc(pi,bm,amws)
      end

      subroutine f2pyinitqgarr7(setupfunc)
      external setupfunc
      double precision xa(208,3)
      double precision xb(208,3)
      double precision b
      common /qgarr7/ xa,xb,b
      call setupfunc(xa,xb,b)
      end

      subroutine f2pyinitqgarr10(setupfunc)
      external setupfunc
      double precision am(7)
      double precision ammu
      common /qgarr10/ am,ammu
      call setupfunc(am,ammu)
      end

      subroutine f2pyinitqgarr15(setupfunc)
      external setupfunc
      double precision fp(3)
      double precision rq(2,3)
      double precision cd(2,3)
      double precision gsoft(3)
      common /qgarr15/ fp,rq,cd,gsoft
      call setupfunc(fp,rq,cd,gsoft)
      end

      subroutine f2pyinitqgarr17(setupfunc)
      external setupfunc
      double precision dels
      double precision alfp
      double precision sigs
      double precision rr
      double precision r3p
      double precision g3p
      double precision delh
      double precision sgap
      common /qgarr17/ dels,alfp,sigs,rr,r3p,g3p,delh,sgap
      call setupfunc(dels,alfp,sigs,rr,r3p,g3p,delh,sgap)
      end

      subroutine f2pyinitqgarr43(setupfunc)
      external setupfunc
      integer moniou
      common /qgarr43/ moniou
      call setupfunc(moniou)
      end

      subroutine f2pyinitarr1(setupfunc)
      external setupfunc
      double precision trnuc(56)
      double precision twsnuc(56)
      double precision twbnuc(56)
      common /arr1/ trnuc,twsnuc,twbnuc
      call setupfunc(trnuc,twsnuc,twbnuc)
      end

      subroutine f2pyinitqgdebug(setupfunc)
      external setupfunc
      integer debug
      common /qgdebug/ debug
      call setupfunc(debug)
      end

      subroutine f2pyinitqgsiinex1(setupfunc)
      external setupfunc
      double precision xan(208,3)
      double precision xbn(208,3)
      double precision bqgs
      double precision bmaxqgs
      double precision bmaxnex
      double precision bminnex
      common /qgsiinex1/ xan,xbn,bqgs,bmaxqgs,bmaxnex,bminnex
      call setupfunc(xan,xbn,bqgs,bmaxqgs,bmaxnex,bminnex)
      end

      subroutine f2pyinitqgarr9(setupfunc)
      external setupfunc
      integer iwp(208)
      integer iwt(208)
      integer lqa(208)
      integer lqb(208)
      integer iprcn(208)
      integer itgcn(208)
      integer ias(1000)
      integer ibs(1000)
      integer nqs(1000)
      integer npompr(1000)
      integer npomtg(1000)
      integer npomin(1000)
      integer nnpr(900,1000)
      integer nntg(900,1000)
      integer ilpr(900,1000)
      integer iltg(900,1000)
      integer lnpr(900,1000)
      integer lntg(900,1000)
      integer nbpi(900,208)
      integer nbti(900,208)
      integer idnpi(900,208)
      integer idnti(900,208)
      integer nppi(900,208)
      integer npti(900,208)
      integer nlpi(900,208)
      integer nlti(900,208)
      common /qgarr9/ iwp,iwt,lqa,lqb,iprcn,itgcn,ias,ibs,nqs,npom
     &pr,npomtg,npomin,nnpr,nntg,ilpr,iltg,lnpr,lntg,nbpi,nbti,idnpi,idn
     &ti,nppi,npti,nlpi,nlti
      call setupfunc(iwp,iwt,lqa,lqb,iprcn,itgcn,ias,ibs,nqs,npomp
     &r,npomtg,npomin,nnpr,nntg,ilpr,iltg,lnpr,lntg,nbpi,nbti,idnpi,idnt
     &i,nppi,npti,nlpi,nlti)
      end

      subroutine f2pyinitqgarr11(setupfunc)
      external setupfunc
      double precision b10
      common /qgarr11/ b10
      call setupfunc(b10)
      end

      subroutine f2pyinitqgarr12(setupfunc)
      external setupfunc
      integer nsp
      common /qgarr12/ nsp
      call setupfunc(nsp)
      end

      subroutine f2pyinitqgarr13(setupfunc)
      external setupfunc
      integer nsf
      integer iaf(208)
      common /qgarr13/ nsf,iaf
      call setupfunc(nsf,iaf)
      end

      subroutine f2pyinitqgarr16(setupfunc)
      external setupfunc
      double precision cc(2,3)
      integer iddp(208)
      integer iddt(208)
      common /qgarr16/ cc,iddp,iddt
      call setupfunc(cc,iddp,iddt)
      end

      subroutine f2pyinitqgarr23(setupfunc)
      external setupfunc
      double precision bbpom(1000)
      double precision vvxpom(1000)
      double precision bpompr(900,208)
      double precision bpomtg(900,208)
      double precision vvxpr(900,208)
      double precision vvxtg(900,208)
      double precision xpompr(900,208)
      double precision xpomtg(900,208)
      double precision xpopin(900,1000)
      double precision xpomin(900,1000)
      double precision vvxin(900,1000)
      double precision bpomin(900,1000)
      common /qgarr23/ bbpom,vvxpom,bpompr,bpomtg,vvxpr,vvxtg,xpom
     &pr,xpomtg,xpopin,xpomin,vvxin,bpomin
      call setupfunc(bbpom,vvxpom,bpompr,bpomtg,vvxpr,vvxtg,xpompr
     &,xpomtg,xpopin,xpomin,vvxin,bpomin)
      end

      subroutine f2pyinitqgarr46(setupfunc)
      external setupfunc
      integer iconab(208,208)
      integer icona(208)
      integer iconb(208)
      common /qgarr46/ iconab,icona,iconb
      call setupfunc(iconab,icona,iconb)
      end

      subroutine f2pyinitqgarr55(setupfunc)
      external setupfunc
      integer nwt
      integer nwp
      common /qgarr55/ nwt,nwp
      call setupfunc(nwt,nwp)
      end

      subroutine f2pyinitqgarr56(setupfunc)
      external setupfunc
      integer nspec
      integer nspect
      common /qgarr56/ nspec,nspect
      call setupfunc(nspec,nspect)
      end

      subroutine f2pyinitjdiff(setupfunc)
      external setupfunc
      double precision bdiff
      integer jdiff
      common /jdiff/ bdiff,jdiff
      call setupfunc(bdiff,jdiff)
      end

      subroutine f2pyinitc2evt(setupfunc)
      external setupfunc
      integer ng1evt
      integer ng2evt
      real rglevt
      real sglevt
      real eglevt
      real fglevt
      integer ikoevt
      double precision typevt
      common /c2evt/ ng1evt,ng2evt,rglevt,sglevt,eglevt,fglevt,iko
     &evt,typevt
      call setupfunc(ng1evt,ng2evt,rglevt,sglevt,eglevt,fglevt,iko
     &evt,typevt)
      end

      subroutine f2pyinitarr3(setupfunc)
      external setupfunc
      double precision x1(7)
      double precision a1(7)
      common /arr3/ x1,a1
      call setupfunc(x1,a1)
      end

      subroutine f2pyinitarr4(setupfunc)
      external setupfunc
      double precision x4(2)
      double precision a4(2)
      common /arr4/ x4,a4
      call setupfunc(x4,a4)
      end

      subroutine f2pyinitarr5(setupfunc)
      external setupfunc
      double precision x5(2)
      double precision a5(2)
      common /arr5/ x5,a5
      call setupfunc(x5,a5)
      end

      subroutine f2pyinitarr8(setupfunc)
      external setupfunc
      double precision x2(4)
      double precision a2
      common /arr8/ x2,a2
      call setupfunc(x2,a2)
      end

      subroutine f2pyinitarr9(setupfunc)
      external setupfunc
      double precision x9(3)
      double precision a9(3)
      common /arr9/ x9,a9
      call setupfunc(x9,a9)
      end

      subroutine f2pyinitqgarr47(setupfunc)
      external setupfunc
      double precision gsect(10,5,6)
      common /qgarr47/ gsect
      call setupfunc(gsect)
      end

      subroutine f2pyinitqgarr48(setupfunc)
      external setupfunc
      double precision qgsasect(10,6,6)
      common /qgarr48/ qgsasect
      call setupfunc(qgsasect)
      end

      subroutine f2pyinitqgarr14(setupfunc)
      external setupfunc
      double precision esp(4,95000)
      integer ich(95000)
      common /qgarr14/ esp,ich
      call setupfunc(esp,ich)
      end

      subroutine f2pyinitqgarr21(setupfunc)
      external setupfunc
      double precision dmmin(3)
      double precision wex(3)
      double precision dmres(3)
      double precision wdres(3)
      common /qgarr21/ dmmin,wex,dmres,wdres
      call setupfunc(dmmin,wex,dmres,wdres)
      end

      subroutine f2pyinitarea40(setupfunc)
      external setupfunc
      integer jdifr
      common /area40/ jdifr
      call setupfunc(jdifr)
      end

      subroutine f2pyinithepevt(setupfunc)
      external setupfunc
      integer nevhep
      integer nhep
      integer isthep(95000)
      integer idhep(95000)
      integer jmohep(2,95000)
      integer jdahep(2,95000)
      double precision phep(5,95000)
      double precision vhep(4,95000)
      common /hepevt/ nevhep,nhep,isthep,idhep,jmohep,jdahep,phep,
     &vhep
      call setupfunc(nevhep,nhep,isthep,idhep,jmohep,jdahep,phep,v
     &hep)
      end

      subroutine f2pyinitqgchg(setupfunc)
      external setupfunc
      integer ichg(95000)
      common /qgchg/ ichg
      call setupfunc(ichg)
      end

      subroutine f2pyinitcrqgslin(setupfunc)
      external setupfunc
      integer ictabl(200)
      integer iqtabl(21)
      common /crqgslin/ ictabl,iqtabl
      call setupfunc(ictabl,iqtabl)
      end

      subroutine f2pyinitnpy(setupfunc)
      external setupfunc
      integer*8 bitgen
      common /npy/ bitgen
      call setupfunc(bitgen)
      end


