C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.23.5)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapqgsect (qgsectf2pywrap, e0n, icz, iap, ia
     &t)
      external qgsect
      double precision e0n
      integer icz
      integer iap
      integer iat
      double precision qgsectf2pywrap, qgsect
      qgsectf2pywrap = qgsect(e0n, icz, iap, iat)
      end


      subroutine f2pyinitqgarr1(setupfunc)
      external setupfunc
      integer ia(2)
      integer icz
      integer icp
      common /qgarr1/ ia,icz,icp
      call setupfunc(ia,icz,icp)
      end

      subroutine f2pyinitqgarr2(setupfunc)
      external setupfunc
      double precision scm
      double precision wp0
      double precision wm0
      common /qgarr2/ scm,wp0,wm0
      call setupfunc(scm,wp0,wm0)
      end

      subroutine f2pyinitqgarr4(setupfunc)
      external setupfunc
      double precision ey0(3)
      common /qgarr4/ ey0
      call setupfunc(ey0)
      end

      subroutine f2pyinitqgarr5(setupfunc)
      external setupfunc
      double precision rnuc(2)
      double precision wsnuc(2)
      double precision wbnuc(2)
      double precision anorm
      double precision cr1(2)
      double precision cr2(2)
      double precision cr3(2)
      common /qgarr5/ rnuc,wsnuc,wbnuc,anorm,cr1,cr2,cr3
      call setupfunc(rnuc,wsnuc,wbnuc,anorm,cr1,cr2,cr3)
      end

      subroutine f2pyinitqgarr6(setupfunc)
      external setupfunc
      double precision pi
      double precision bm
      double precision amws
      common /qgarr6/ pi,bm,amws
      call setupfunc(pi,bm,amws)
      end

      subroutine f2pyinitqgarr7(setupfunc)
      external setupfunc
      double precision xa(207,3)
      double precision xb(207,3)
      double precision b
      common /qgarr7/ xa,xb,b
      call setupfunc(xa,xb,b)
      end

      subroutine f2pyinitqgarr10(setupfunc)
      external setupfunc
      double precision am(7)
      double precision ammu
      common /qgarr10/ am,ammu
      call setupfunc(am,ammu)
      end

      subroutine f2pyinitqgarr15(setupfunc)
      external setupfunc
      double precision fp(3)
      double precision rq(3)
      double precision cd(2,3)
      common /qgarr15/ fp,rq,cd
      call setupfunc(fp,rq,cd)
      end

      subroutine f2pyinitqgarr17(setupfunc)
      external setupfunc
      double precision dels
      double precision alfp
      double precision sigs
      double precision rr
      double precision r3p
      double precision g3p
      double precision alpd
      double precision delh
      common /qgarr17/ dels,alfp,sigs,rr,r3p,g3p,alpd,delh
      call setupfunc(dels,alfp,sigs,rr,r3p,g3p,alpd,delh)
      end

      subroutine f2pyinitqgarr43(setupfunc)
      external setupfunc
      integer moniou
      common /qgarr43/ moniou
      call setupfunc(moniou)
      end

      subroutine f2pyinitqgarr49(setupfunc)
      external setupfunc
      double precision trnuc(56)
      double precision twsnuc(56)
      double precision twbnuc(56)
      common /qgarr49/ trnuc,twsnuc,twbnuc
      call setupfunc(trnuc,twsnuc,twbnuc)
      end

      subroutine f2pyinitdebug(setupfunc)
      external setupfunc
      integer debug
      common /debug/ debug
      call setupfunc(debug)
      end

      subroutine f2pyinitqgarr9(setupfunc)
      external setupfunc
      integer iwp(207)
      integer iwt(207)
      integer lqa(207)
      integer lqb(207)
      integer iprcn(207)
      integer itgcn(207)
      integer ias(1000)
      integer ibs(1000)
      integer nqs(1000)
      integer npompr(1000)
      integer npomtg(1000)
      integer npomin(1000)
      integer nnpr(5000,1000)
      integer nntg(5000,1000)
      integer ilpr(900,1000)
      integer iltg(900,1000)
      integer lnpr(900,1000)
      integer lntg(900,1000)
      integer nbpi(1000,207)
      integer nbti(1000,207)
      integer idnpi(1000,207)
      integer idnti(1000,207)
      integer nppi(1000,207)
      integer npti(1000,207)
      integer nlpi(1000,207)
      integer nlti(1000,207)
      common /qgarr9/ iwp,iwt,lqa,lqb,iprcn,itgcn,ias,ibs,nqs,npom
     &pr,npomtg,npomin,nnpr,nntg,ilpr,iltg,lnpr,lntg,nbpi,nbti,idnpi,idn
     &ti,nppi,npti,nlpi,nlti
      call setupfunc(iwp,iwt,lqa,lqb,iprcn,itgcn,ias,ibs,nqs,npomp
     &r,npomtg,npomin,nnpr,nntg,ilpr,iltg,lnpr,lntg,nbpi,nbti,idnpi,idnt
     &i,nppi,npti,nlpi,nlti)
      end

      subroutine f2pyinitqgarr11(setupfunc)
      external setupfunc
      double precision b10
      common /qgarr11/ b10
      call setupfunc(b10)
      end

      subroutine f2pyinitqgarr12(setupfunc)
      external setupfunc
      integer nsp
      common /qgarr12/ nsp
      call setupfunc(nsp)
      end

      subroutine f2pyinitqgarr13(setupfunc)
      external setupfunc
      integer nsf
      integer iaf(207)
      common /qgarr13/ nsf,iaf
      call setupfunc(nsf,iaf)
      end

      subroutine f2pyinitqgarr16(setupfunc)
      external setupfunc
      double precision cc(2,3)
      integer iddp(207)
      integer iddt(207)
      common /qgarr16/ cc,iddp,iddt
      call setupfunc(cc,iddp,iddt)
      end

      subroutine f2pyinitqgarr22(setupfunc)
      external setupfunc
      double precision wppr(207)
      double precision wmtg(207)
      common /qgarr22/ wppr,wmtg
      call setupfunc(wppr,wmtg)
      end

      subroutine f2pyinitqgarr23(setupfunc)
      external setupfunc
      double precision bbpom(1000)
      double precision vvxpom(1000)
      double precision bpompr(1000,207)
      double precision bpomtg(1000,207)
      double precision vvxpr(1000,207)
      double precision vvxtg(1000,207)
      double precision xpompr(1000,207)
      double precision xpomtg(1000,207)
      double precision xpopin(5000,1000)
      double precision xpomin(5000,1000)
      common /qgarr23/ bbpom,vvxpom,bpompr,bpomtg,vvxpr,vvxtg,xpom
     &pr,xpomtg,xpopin,xpomin
      call setupfunc(bbpom,vvxpom,bpompr,bpomtg,vvxpr,vvxtg,xpompr
     &,xpomtg,xpopin,xpomin)
      end

      subroutine f2pyinitqgarr46(setupfunc)
      external setupfunc
      integer iconab(207,207)
      integer icona(207)
      integer iconb(207)
      common /qgarr46/ iconab,icona,iconb
      call setupfunc(iconab,icona,iconb)
      end

      subroutine f2pyinitqgarr55(setupfunc)
      external setupfunc
      integer nwt
      integer nwp
      common /qgarr55/ nwt,nwp
      call setupfunc(nwt,nwp)
      end

      subroutine f2pyinitqgarr14(setupfunc)
      external setupfunc
      double precision esp(4,95000)
      integer ich(95000)
      common /qgarr14/ esp,ich
      call setupfunc(esp,ich)
      end

      subroutine f2pyinitqgarr21(setupfunc)
      external setupfunc
      double precision dmmin(3)
      double precision wex(3)
      common /qgarr21/ dmmin,wex
      call setupfunc(dmmin,wex)
      end

      subroutine f2pyinitqgarr47(setupfunc)
      external setupfunc
      double precision gsect(10,5,6)
      common /qgarr47/ gsect
      call setupfunc(gsect)
      end

      subroutine f2pyinitqgarr48(setupfunc)
      external setupfunc
      double precision asect(10,6,6)
      common /qgarr48/ asect
      call setupfunc(asect)
      end

      subroutine f2pyinitqgarr50(setupfunc)
      external setupfunc
      double precision x1(7)
      double precision a1(7)
      common /qgarr50/ x1,a1
      call setupfunc(x1,a1)
      end

      subroutine f2pyinitqgarr51(setupfunc)
      external setupfunc
      double precision x4(2)
      double precision a4(2)
      common /qgarr51/ x4,a4
      call setupfunc(x4,a4)
      end

      subroutine f2pyinitqgarr52(setupfunc)
      external setupfunc
      double precision x2(4)
      double precision a2
      common /qgarr52/ x2,a2
      call setupfunc(x2,a2)
      end

      subroutine f2pyinitqgarr53(setupfunc)
      external setupfunc
      double precision x9(3)
      double precision a9(3)
      common /qgarr53/ x9,a9
      call setupfunc(x9,a9)
      end


