/* File: _rmmardrngmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Dec 19 08:30:11 2022
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_rmmardrng_error;
static PyObject *_rmmardrng_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _rmmardrng_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _rmmardrng_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(rmmaqd,RMMAQD)(int*,int*,string,size_t);
extern void F_FUNC(rmmard,RMMARD)(double*,int*,int*);
extern void F_WRAPPEDFUNC(simrnd,SIMRND)(double*);
extern void F_FUNC_US(init_rmmard,INIT_RMMARD)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** rmmaqd ***********************************/
static char doc_f2py_rout__rmmardrng_rmmaqd[] = "\
rmmaqd(iseed,iseq,chopt)\n\nWrapper for ``rmmaqd``.\
\n\nParameters\n----------\n"
"iseed : input rank-1 array('i') with bounds (3)\n"
"iseq : input int\n"
"chopt : input string(len=-1)";
/* extern void F_FUNC(rmmaqd,RMMAQD)(int*,int*,string,size_t); */
static PyObject *f2py_rout__rmmardrng_rmmaqd(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,string,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int *iseed = NULL;
  npy_intp iseed_Dims[1] = {-1};
  const int iseed_Rank = 1;
  PyArrayObject *capi_iseed_tmp = NULL;
  int capi_iseed_intent = 0;
  PyObject *iseed_capi = Py_None;
  int iseq = 0;
  PyObject *iseq_capi = Py_None;
  string chopt = NULL;
  int slen(chopt);
  PyObject *chopt_capi = Py_None;
  static char *capi_kwlist[] = {"iseed","iseq","chopt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|:_rmmardrng.rmmaqd",\
    capi_kwlist,&iseed_capi,&iseq_capi,&chopt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iseed */
  iseed_Dims[0]=3;
  capi_iseed_intent |= F2PY_INTENT_IN;
  capi_iseed_tmp = array_from_pyobj(NPY_INT,iseed_Dims,iseed_Rank,capi_iseed_intent,iseed_capi);
  if (capi_iseed_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _rmmardrng_error,"failed in converting 1st argument `iseed' of _rmmardrng.rmmaqd to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    iseed = (int *)(PyArray_DATA(capi_iseed_tmp));

  /* Processing variable iseq */
    f2py_success = int_from_pyobj(&iseq,iseq_capi,"_rmmardrng.rmmaqd() 2nd argument (iseq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable chopt */
  slen(chopt) = -1;
  f2py_success = string_from_pyobj(&chopt,&slen(chopt),"",chopt_capi,"string_from_pyobj failed in converting 3rd argument `chopt' of _rmmardrng.rmmaqd to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(iseed,&iseq,chopt,slen(chopt));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(chopt);
  }  /*if (f2py_success) of chopt*/
  /* End of cleaning variable chopt */
  } /*if (f2py_success) of iseq*/
  /* End of cleaning variable iseq */
  if((PyObject *)capi_iseed_tmp!=iseed_capi) {
    Py_XDECREF(capi_iseed_tmp); }
  }  /*if (capi_iseed_tmp == NULL) ... else of iseed*/
  /* End of cleaning variable iseed */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of rmmaqd *******************************/

/*********************************** rmmard ***********************************/
static char doc_f2py_rout__rmmardrng_rmmard[] = "\
rmmard(rvec,lenv,iseq)\n\nWrapper for ``rmmard``.\
\n\nParameters\n----------\n"
"rvec : input rank-1 array('d') with bounds (*)\n"
"lenv : input int\n"
"iseq : input int";
/* extern void F_FUNC(rmmard,RMMARD)(double*,int*,int*); */
static PyObject *f2py_rout__rmmardrng_rmmard(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *rvec = NULL;
  npy_intp rvec_Dims[1] = {-1};
  const int rvec_Rank = 1;
  PyArrayObject *capi_rvec_tmp = NULL;
  int capi_rvec_intent = 0;
  PyObject *rvec_capi = Py_None;
  int lenv = 0;
  PyObject *lenv_capi = Py_None;
  int iseq = 0;
  PyObject *iseq_capi = Py_None;
  static char *capi_kwlist[] = {"rvec","lenv","iseq",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|:_rmmardrng.rmmard",\
    capi_kwlist,&rvec_capi,&lenv_capi,&iseq_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rvec */
  ;
  capi_rvec_intent |= F2PY_INTENT_IN;
  capi_rvec_tmp = array_from_pyobj(NPY_DOUBLE,rvec_Dims,rvec_Rank,capi_rvec_intent,rvec_capi);
  if (capi_rvec_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : _rmmardrng_error,"failed in converting 1st argument `rvec' of _rmmardrng.rmmard to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    rvec = (double *)(PyArray_DATA(capi_rvec_tmp));

  /* Processing variable lenv */
    f2py_success = int_from_pyobj(&lenv,lenv_capi,"_rmmardrng.rmmard() 2nd argument (lenv) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iseq */
    f2py_success = int_from_pyobj(&iseq,iseq_capi,"_rmmardrng.rmmard() 3rd argument (iseq) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(rvec,&lenv,&iseq);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of iseq*/
  /* End of cleaning variable iseq */
  } /*if (f2py_success) of lenv*/
  /* End of cleaning variable lenv */
  if((PyObject *)capi_rvec_tmp!=rvec_capi) {
    Py_XDECREF(capi_rvec_tmp); }
  }  /*if (capi_rvec_tmp == NULL) ... else of rvec*/
  /* End of cleaning variable rvec */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of rmmard *******************************/

/*********************************** simrnd ***********************************/
static char doc_f2py_rout__rmmardrng_simrnd[] = "\
simrnd = simrnd()\n\nWrapper for ``simrnd``.\
\n\nReturns\n-------\n"
"simrnd : float";
/* extern void F_WRAPPEDFUNC(simrnd,SIMRND)(double*); */
static PyObject *f2py_rout__rmmardrng_simrnd(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double simrnd = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "|:_rmmardrng.simrnd",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable simrnd */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&simrnd);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",simrnd);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable simrnd */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of simrnd *******************************/

/******************************** init_rmmard ********************************/
static char doc_f2py_rout__rmmardrng_init_rmmard[] = "\
init_rmmard(iseedin)\n\nWrapper for ``init_rmmard``.\
\n\nParameters\n----------\n"
"iseedin : input int";
/* extern void F_FUNC_US(init_rmmard,INIT_RMMARD)(int*); */
static PyObject *f2py_rout__rmmardrng_init_rmmard(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iseedin = 0;
  PyObject *iseedin_capi = Py_None;
  static char *capi_kwlist[] = {"iseedin",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|:_rmmardrng.init_rmmard",\
    capi_kwlist,&iseedin_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iseedin */
    f2py_success = int_from_pyobj(&iseedin,iseedin_capi,"_rmmardrng.init_rmmard() 1st argument (iseedin) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iseedin);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of iseedin*/
  /* End of cleaning variable iseedin */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of init_rmmard *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_crranma3_def[] = {
  {"cd",0,{{-1}},NPY_DOUBLE},
  {"cint",0,{{-1}},NPY_DOUBLE},
  {"cm",0,{{-1}},NPY_DOUBLE},
  {"twom24",0,{{-1}},NPY_DOUBLE},
  {"twom48",0,{{-1}},NPY_DOUBLE},
  {"modcns",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_crranma3(char *cd,char *cint,char *cm,char *twom24,char *twom48,char *modcns) {
  int i_f2py=0;
  f2py_crranma3_def[i_f2py++].data = cd;
  f2py_crranma3_def[i_f2py++].data = cint;
  f2py_crranma3_def[i_f2py++].data = cm;
  f2py_crranma3_def[i_f2py++].data = twom24;
  f2py_crranma3_def[i_f2py++].data = twom48;
  f2py_crranma3_def[i_f2py++].data = modcns;
}
extern void F_FUNC(f2pyinitcrranma3,F2PYINITCRRANMA3)(void(*)(char*,char*,char*,char*,char*,char*));
static void f2py_init_crranma3(void) {
  F_FUNC(f2pyinitcrranma3,F2PYINITCRRANMA3)(f2py_setup_crranma3);
}

static FortranDataDef f2py_crranma4_def[] = {
  {"c",1,{{8}},NPY_DOUBLE},
  {"u",2,{{97,8}},NPY_DOUBLE},
  {"ijkl",1,{{8}},NPY_INT},
  {"i97",1,{{8}},NPY_INT},
  {"j97",1,{{8}},NPY_INT},
  {"ntot",1,{{8}},NPY_INT},
  {"ntot2",1,{{8}},NPY_INT},
  {"jseq",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_crranma4(char *c,char *u,char *ijkl,char *i97,char *j97,char *ntot,char *ntot2,char *jseq) {
  int i_f2py=0;
  f2py_crranma4_def[i_f2py++].data = c;
  f2py_crranma4_def[i_f2py++].data = u;
  f2py_crranma4_def[i_f2py++].data = ijkl;
  f2py_crranma4_def[i_f2py++].data = i97;
  f2py_crranma4_def[i_f2py++].data = j97;
  f2py_crranma4_def[i_f2py++].data = ntot;
  f2py_crranma4_def[i_f2py++].data = ntot2;
  f2py_crranma4_def[i_f2py++].data = jseq;
}
extern void F_FUNC(f2pyinitcrranma4,F2PYINITCRRANMA4)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_crranma4(void) {
  F_FUNC(f2pyinitcrranma4,F2PYINITCRRANMA4)(f2py_setup_crranma4);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"rmmaqd",-1,{{-1}},0,(char *)F_FUNC(rmmaqd,RMMAQD),(f2py_init_func)f2py_rout__rmmardrng_rmmaqd,doc_f2py_rout__rmmardrng_rmmaqd},
  {"rmmard",-1,{{-1}},0,(char *)F_FUNC(rmmard,RMMARD),(f2py_init_func)f2py_rout__rmmardrng_rmmard,doc_f2py_rout__rmmardrng_rmmard},
  {"simrnd",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(simrnd,SIMRND),(f2py_init_func)f2py_rout__rmmardrng_simrnd,doc_f2py_rout__rmmardrng_simrnd},
  {"init_rmmard",-1,{{-1}},0,(char *)F_FUNC_US(init_rmmard,INIT_RMMARD),(f2py_init_func)f2py_rout__rmmardrng_init_rmmard,doc_f2py_rout__rmmardrng_init_rmmard},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "_rmmardrng",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit__rmmardrng(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = _rmmardrng_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module _rmmardrng (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module '_rmmardrng' is auto-generated with f2py (version:2).\nFunctions:\n"
"  rmmaqd(iseed,iseq,chopt)\n"
"  rmmard(rvec,lenv,iseq)\n"
"  simrnd = simrnd()\n"
"  init_rmmard(iseedin)\n"
"COMMON blocks:\n""  /crranma3/ cd,cint,cm,twom24,twom48,modcns\n""  /crranma4/ c(8),u(97,8),ijkl(8),i97(8),j97(8),ntot(8),ntot2(8),jseq\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  _rmmardrng_error = PyErr_NewException ("_rmmardrng.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "__rmmardrng_error", _rmmardrng_error);
  Py_DECREF(_rmmardrng_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }



    {
      extern double F_FUNC(simrnd,SIMRND)(void);
      PyObject* o = PyDict_GetItemString(d,"simrnd");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(simrnd,SIMRND),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("simrnd");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  tmp = PyFortranObject_New(f2py_crranma3_def,f2py_init_crranma3);
  F2PyDict_SetItemString(d, "crranma3", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_crranma4_def,f2py_init_crranma4);
  F2PyDict_SetItemString(d, "crranma4", tmp);
  Py_DECREF(tmp);
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"_rmmardrng");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
