/* File: _qgsII04module.c
 * This file is auto-generated with f2py (version:1.23.5).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Jan 16 05:25:59 2023
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_qgsII04_error;
static PyObject *_qgsII04_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _qgsII04_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _qgsII04_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(qgini,QGINI)(double*,int*,int*,int*);
extern void F_FUNC(qgconf,QGCONF)(void);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** qgini ***********************************/
static char doc_f2py_rout__qgsII04_qgini[] = "\
qgini(e0n,icp0,iap,iat)\n\nWrapper for ``qgini``.\
\n\nParameters\n----------\n"
"e0n : input float\n"
"icp0 : input int\n"
"iap : input int\n"
"iat : input int";
/* extern void F_FUNC(qgini,QGINI)(double*,int*,int*,int*); */
static PyObject *f2py_rout__qgsII04_qgini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double e0n = 0;
    PyObject *e0n_capi = Py_None;
    int icp0 = 0;
    PyObject *icp0_capi = Py_None;
    int iap = 0;
    PyObject *iap_capi = Py_None;
    int iat = 0;
    PyObject *iat_capi = Py_None;
    static char *capi_kwlist[] = {"e0n","icp0","iap","iat",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:_qgsII04.qgini",\
        capi_kwlist,&e0n_capi,&icp0_capi,&iap_capi,&iat_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable e0n */
        f2py_success = double_from_pyobj(&e0n,e0n_capi,"_qgsII04.qgini() 1st argument (e0n) can't be converted to double");
    if (f2py_success) {
    /* Processing variable icp0 */
        f2py_success = int_from_pyobj(&icp0,icp0_capi,"_qgsII04.qgini() 2nd argument (icp0) can't be converted to int");
    if (f2py_success) {
    /* Processing variable iap */
        f2py_success = int_from_pyobj(&iap,iap_capi,"_qgsII04.qgini() 3rd argument (iap) can't be converted to int");
    if (f2py_success) {
    /* Processing variable iat */
        f2py_success = int_from_pyobj(&iat,iat_capi,"_qgsII04.qgini() 4th argument (iat) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&e0n,&icp0,&iap,&iat);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of iat*/
    /* End of cleaning variable iat */
    } /*if (f2py_success) of iap*/
    /* End of cleaning variable iap */
    } /*if (f2py_success) of icp0*/
    /* End of cleaning variable icp0 */
    } /*if (f2py_success) of e0n*/
    /* End of cleaning variable e0n */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of qgini ********************************/

/*********************************** qgconf ***********************************/
static char doc_f2py_rout__qgsII04_qgconf[] = "\
qgconf()\n\nWrapper for ``qgconf``.\
\n";
/* extern void F_FUNC(qgconf,QGCONF)(void); */
static PyObject *f2py_rout__qgsII04_qgconf(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_qgsII04.qgconf",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of qgconf *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_qgarr1_def[] = {
  {"ia",1,{{2}},NPY_INT},
  {"icz",0,{{-1}},NPY_INT},
  {"icp",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr1(char *ia,char *icz,char *icp) {
  int i_f2py=0;
  f2py_qgarr1_def[i_f2py++].data = ia;
  f2py_qgarr1_def[i_f2py++].data = icz;
  f2py_qgarr1_def[i_f2py++].data = icp;
}
extern void F_FUNC(f2pyinitqgarr1,F2PYINITQGARR1)(void(*)(char*,char*,char*));
static void f2py_init_qgarr1(void) {
  F_FUNC(f2pyinitqgarr1,F2PYINITQGARR1)(f2py_setup_qgarr1);
}

static FortranDataDef f2py_qgarr2_def[] = {
  {"scm",0,{{-1}},NPY_DOUBLE},
  {"wp0",0,{{-1}},NPY_DOUBLE},
  {"wm0",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr2(char *scm,char *wp0,char *wm0) {
  int i_f2py=0;
  f2py_qgarr2_def[i_f2py++].data = scm;
  f2py_qgarr2_def[i_f2py++].data = wp0;
  f2py_qgarr2_def[i_f2py++].data = wm0;
}
extern void F_FUNC(f2pyinitqgarr2,F2PYINITQGARR2)(void(*)(char*,char*,char*));
static void f2py_init_qgarr2(void) {
  F_FUNC(f2pyinitqgarr2,F2PYINITQGARR2)(f2py_setup_qgarr2);
}

static FortranDataDef f2py_qgarr4_def[] = {
  {"ey0",1,{{3}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr4(char *ey0) {
  int i_f2py=0;
  f2py_qgarr4_def[i_f2py++].data = ey0;
}
extern void F_FUNC(f2pyinitqgarr4,F2PYINITQGARR4)(void(*)(char*));
static void f2py_init_qgarr4(void) {
  F_FUNC(f2pyinitqgarr4,F2PYINITQGARR4)(f2py_setup_qgarr4);
}

static FortranDataDef f2py_qgarr5_def[] = {
  {"rnuc",1,{{2}},NPY_DOUBLE},
  {"wsnuc",1,{{2}},NPY_DOUBLE},
  {"wbnuc",1,{{2}},NPY_DOUBLE},
  {"anorm",0,{{-1}},NPY_DOUBLE},
  {"cr1",1,{{2}},NPY_DOUBLE},
  {"cr2",1,{{2}},NPY_DOUBLE},
  {"cr3",1,{{2}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr5(char *rnuc,char *wsnuc,char *wbnuc,char *anorm,char *cr1,char *cr2,char *cr3) {
  int i_f2py=0;
  f2py_qgarr5_def[i_f2py++].data = rnuc;
  f2py_qgarr5_def[i_f2py++].data = wsnuc;
  f2py_qgarr5_def[i_f2py++].data = wbnuc;
  f2py_qgarr5_def[i_f2py++].data = anorm;
  f2py_qgarr5_def[i_f2py++].data = cr1;
  f2py_qgarr5_def[i_f2py++].data = cr2;
  f2py_qgarr5_def[i_f2py++].data = cr3;
}
extern void F_FUNC(f2pyinitqgarr5,F2PYINITQGARR5)(void(*)(char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_qgarr5(void) {
  F_FUNC(f2pyinitqgarr5,F2PYINITQGARR5)(f2py_setup_qgarr5);
}

static FortranDataDef f2py_qgarr6_def[] = {
  {"pi",0,{{-1}},NPY_DOUBLE},
  {"bm",0,{{-1}},NPY_DOUBLE},
  {"amws",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr6(char *pi,char *bm,char *amws) {
  int i_f2py=0;
  f2py_qgarr6_def[i_f2py++].data = pi;
  f2py_qgarr6_def[i_f2py++].data = bm;
  f2py_qgarr6_def[i_f2py++].data = amws;
}
extern void F_FUNC(f2pyinitqgarr6,F2PYINITQGARR6)(void(*)(char*,char*,char*));
static void f2py_init_qgarr6(void) {
  F_FUNC(f2pyinitqgarr6,F2PYINITQGARR6)(f2py_setup_qgarr6);
}

static FortranDataDef f2py_qgarr7_def[] = {
  {"xa",2,{{208,3}},NPY_DOUBLE},
  {"xb",2,{{208,3}},NPY_DOUBLE},
  {"b",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr7(char *xa,char *xb,char *b) {
  int i_f2py=0;
  f2py_qgarr7_def[i_f2py++].data = xa;
  f2py_qgarr7_def[i_f2py++].data = xb;
  f2py_qgarr7_def[i_f2py++].data = b;
}
extern void F_FUNC(f2pyinitqgarr7,F2PYINITQGARR7)(void(*)(char*,char*,char*));
static void f2py_init_qgarr7(void) {
  F_FUNC(f2pyinitqgarr7,F2PYINITQGARR7)(f2py_setup_qgarr7);
}

static FortranDataDef f2py_qgarr10_def[] = {
  {"am",1,{{7}},NPY_DOUBLE},
  {"ammu",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr10(char *am,char *ammu) {
  int i_f2py=0;
  f2py_qgarr10_def[i_f2py++].data = am;
  f2py_qgarr10_def[i_f2py++].data = ammu;
}
extern void F_FUNC(f2pyinitqgarr10,F2PYINITQGARR10)(void(*)(char*,char*));
static void f2py_init_qgarr10(void) {
  F_FUNC(f2pyinitqgarr10,F2PYINITQGARR10)(f2py_setup_qgarr10);
}

static FortranDataDef f2py_qgarr15_def[] = {
  {"fp",1,{{3}},NPY_DOUBLE},
  {"rq",2,{{2,3}},NPY_DOUBLE},
  {"cd",2,{{2,3}},NPY_DOUBLE},
  {"gsoft",1,{{3}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr15(char *fp,char *rq,char *cd,char *gsoft) {
  int i_f2py=0;
  f2py_qgarr15_def[i_f2py++].data = fp;
  f2py_qgarr15_def[i_f2py++].data = rq;
  f2py_qgarr15_def[i_f2py++].data = cd;
  f2py_qgarr15_def[i_f2py++].data = gsoft;
}
extern void F_FUNC(f2pyinitqgarr15,F2PYINITQGARR15)(void(*)(char*,char*,char*,char*));
static void f2py_init_qgarr15(void) {
  F_FUNC(f2pyinitqgarr15,F2PYINITQGARR15)(f2py_setup_qgarr15);
}

static FortranDataDef f2py_qgarr17_def[] = {
  {"dels",0,{{-1}},NPY_DOUBLE},
  {"alfp",0,{{-1}},NPY_DOUBLE},
  {"sigs",0,{{-1}},NPY_DOUBLE},
  {"rr",0,{{-1}},NPY_DOUBLE},
  {"r3p",0,{{-1}},NPY_DOUBLE},
  {"g3p",0,{{-1}},NPY_DOUBLE},
  {"delh",0,{{-1}},NPY_DOUBLE},
  {"sgap",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr17(char *dels,char *alfp,char *sigs,char *rr,char *r3p,char *g3p,char *delh,char *sgap) {
  int i_f2py=0;
  f2py_qgarr17_def[i_f2py++].data = dels;
  f2py_qgarr17_def[i_f2py++].data = alfp;
  f2py_qgarr17_def[i_f2py++].data = sigs;
  f2py_qgarr17_def[i_f2py++].data = rr;
  f2py_qgarr17_def[i_f2py++].data = r3p;
  f2py_qgarr17_def[i_f2py++].data = g3p;
  f2py_qgarr17_def[i_f2py++].data = delh;
  f2py_qgarr17_def[i_f2py++].data = sgap;
}
extern void F_FUNC(f2pyinitqgarr17,F2PYINITQGARR17)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_qgarr17(void) {
  F_FUNC(f2pyinitqgarr17,F2PYINITQGARR17)(f2py_setup_qgarr17);
}

static FortranDataDef f2py_qgarr43_def[] = {
  {"moniou",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr43(char *moniou) {
  int i_f2py=0;
  f2py_qgarr43_def[i_f2py++].data = moniou;
}
extern void F_FUNC(f2pyinitqgarr43,F2PYINITQGARR43)(void(*)(char*));
static void f2py_init_qgarr43(void) {
  F_FUNC(f2pyinitqgarr43,F2PYINITQGARR43)(f2py_setup_qgarr43);
}

static FortranDataDef f2py_arr1_def[] = {
  {"trnuc",1,{{56}},NPY_DOUBLE},
  {"twsnuc",1,{{56}},NPY_DOUBLE},
  {"twbnuc",1,{{56}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_arr1(char *trnuc,char *twsnuc,char *twbnuc) {
  int i_f2py=0;
  f2py_arr1_def[i_f2py++].data = trnuc;
  f2py_arr1_def[i_f2py++].data = twsnuc;
  f2py_arr1_def[i_f2py++].data = twbnuc;
}
extern void F_FUNC(f2pyinitarr1,F2PYINITARR1)(void(*)(char*,char*,char*));
static void f2py_init_arr1(void) {
  F_FUNC(f2pyinitarr1,F2PYINITARR1)(f2py_setup_arr1);
}

static FortranDataDef f2py_qgdebug_def[] = {
  {"debug",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgdebug(char *debug) {
  int i_f2py=0;
  f2py_qgdebug_def[i_f2py++].data = debug;
}
extern void F_FUNC(f2pyinitqgdebug,F2PYINITQGDEBUG)(void(*)(char*));
static void f2py_init_qgdebug(void) {
  F_FUNC(f2pyinitqgdebug,F2PYINITQGDEBUG)(f2py_setup_qgdebug);
}

static FortranDataDef f2py_qgsiinex1_def[] = {
  {"xan",2,{{208,3}},NPY_DOUBLE},
  {"xbn",2,{{208,3}},NPY_DOUBLE},
  {"bqgs",0,{{-1}},NPY_DOUBLE},
  {"bmaxqgs",0,{{-1}},NPY_DOUBLE},
  {"bmaxnex",0,{{-1}},NPY_DOUBLE},
  {"bminnex",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgsiinex1(char *xan,char *xbn,char *bqgs,char *bmaxqgs,char *bmaxnex,char *bminnex) {
  int i_f2py=0;
  f2py_qgsiinex1_def[i_f2py++].data = xan;
  f2py_qgsiinex1_def[i_f2py++].data = xbn;
  f2py_qgsiinex1_def[i_f2py++].data = bqgs;
  f2py_qgsiinex1_def[i_f2py++].data = bmaxqgs;
  f2py_qgsiinex1_def[i_f2py++].data = bmaxnex;
  f2py_qgsiinex1_def[i_f2py++].data = bminnex;
}
extern void F_FUNC(f2pyinitqgsiinex1,F2PYINITQGSIINEX1)(void(*)(char*,char*,char*,char*,char*,char*));
static void f2py_init_qgsiinex1(void) {
  F_FUNC(f2pyinitqgsiinex1,F2PYINITQGSIINEX1)(f2py_setup_qgsiinex1);
}

static FortranDataDef f2py_qgarr9_def[] = {
  {"iwp",1,{{208}},NPY_INT},
  {"iwt",1,{{208}},NPY_INT},
  {"lqa",1,{{208}},NPY_INT},
  {"lqb",1,{{208}},NPY_INT},
  {"iprcn",1,{{208}},NPY_INT},
  {"itgcn",1,{{208}},NPY_INT},
  {"ias",1,{{1000}},NPY_INT},
  {"ibs",1,{{1000}},NPY_INT},
  {"nqs",1,{{1000}},NPY_INT},
  {"npompr",1,{{1000}},NPY_INT},
  {"npomtg",1,{{1000}},NPY_INT},
  {"npomin",1,{{1000}},NPY_INT},
  {"nnpr",2,{{900,1000}},NPY_INT},
  {"nntg",2,{{900,1000}},NPY_INT},
  {"ilpr",2,{{900,1000}},NPY_INT},
  {"iltg",2,{{900,1000}},NPY_INT},
  {"lnpr",2,{{900,1000}},NPY_INT},
  {"lntg",2,{{900,1000}},NPY_INT},
  {"nbpi",2,{{900,208}},NPY_INT},
  {"nbti",2,{{900,208}},NPY_INT},
  {"idnpi",2,{{900,208}},NPY_INT},
  {"idnti",2,{{900,208}},NPY_INT},
  {"nppi",2,{{900,208}},NPY_INT},
  {"npti",2,{{900,208}},NPY_INT},
  {"nlpi",2,{{900,208}},NPY_INT},
  {"nlti",2,{{900,208}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr9(char *iwp,char *iwt,char *lqa,char *lqb,char *iprcn,char *itgcn,char *ias,char *ibs,char *nqs,char *npompr,char *npomtg,char *npomin,char *nnpr,char *nntg,char *ilpr,char *iltg,char *lnpr,char *lntg,char *nbpi,char *nbti,char *idnpi,char *idnti,char *nppi,char *npti,char *nlpi,char *nlti) {
  int i_f2py=0;
  f2py_qgarr9_def[i_f2py++].data = iwp;
  f2py_qgarr9_def[i_f2py++].data = iwt;
  f2py_qgarr9_def[i_f2py++].data = lqa;
  f2py_qgarr9_def[i_f2py++].data = lqb;
  f2py_qgarr9_def[i_f2py++].data = iprcn;
  f2py_qgarr9_def[i_f2py++].data = itgcn;
  f2py_qgarr9_def[i_f2py++].data = ias;
  f2py_qgarr9_def[i_f2py++].data = ibs;
  f2py_qgarr9_def[i_f2py++].data = nqs;
  f2py_qgarr9_def[i_f2py++].data = npompr;
  f2py_qgarr9_def[i_f2py++].data = npomtg;
  f2py_qgarr9_def[i_f2py++].data = npomin;
  f2py_qgarr9_def[i_f2py++].data = nnpr;
  f2py_qgarr9_def[i_f2py++].data = nntg;
  f2py_qgarr9_def[i_f2py++].data = ilpr;
  f2py_qgarr9_def[i_f2py++].data = iltg;
  f2py_qgarr9_def[i_f2py++].data = lnpr;
  f2py_qgarr9_def[i_f2py++].data = lntg;
  f2py_qgarr9_def[i_f2py++].data = nbpi;
  f2py_qgarr9_def[i_f2py++].data = nbti;
  f2py_qgarr9_def[i_f2py++].data = idnpi;
  f2py_qgarr9_def[i_f2py++].data = idnti;
  f2py_qgarr9_def[i_f2py++].data = nppi;
  f2py_qgarr9_def[i_f2py++].data = npti;
  f2py_qgarr9_def[i_f2py++].data = nlpi;
  f2py_qgarr9_def[i_f2py++].data = nlti;
}
extern void F_FUNC(f2pyinitqgarr9,F2PYINITQGARR9)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_qgarr9(void) {
  F_FUNC(f2pyinitqgarr9,F2PYINITQGARR9)(f2py_setup_qgarr9);
}

static FortranDataDef f2py_qgarr11_def[] = {
  {"b10",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr11(char *b10) {
  int i_f2py=0;
  f2py_qgarr11_def[i_f2py++].data = b10;
}
extern void F_FUNC(f2pyinitqgarr11,F2PYINITQGARR11)(void(*)(char*));
static void f2py_init_qgarr11(void) {
  F_FUNC(f2pyinitqgarr11,F2PYINITQGARR11)(f2py_setup_qgarr11);
}

static FortranDataDef f2py_qgarr12_def[] = {
  {"nsp",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr12(char *nsp) {
  int i_f2py=0;
  f2py_qgarr12_def[i_f2py++].data = nsp;
}
extern void F_FUNC(f2pyinitqgarr12,F2PYINITQGARR12)(void(*)(char*));
static void f2py_init_qgarr12(void) {
  F_FUNC(f2pyinitqgarr12,F2PYINITQGARR12)(f2py_setup_qgarr12);
}

static FortranDataDef f2py_qgarr13_def[] = {
  {"nsf",0,{{-1}},NPY_INT},
  {"iaf",1,{{208}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr13(char *nsf,char *iaf) {
  int i_f2py=0;
  f2py_qgarr13_def[i_f2py++].data = nsf;
  f2py_qgarr13_def[i_f2py++].data = iaf;
}
extern void F_FUNC(f2pyinitqgarr13,F2PYINITQGARR13)(void(*)(char*,char*));
static void f2py_init_qgarr13(void) {
  F_FUNC(f2pyinitqgarr13,F2PYINITQGARR13)(f2py_setup_qgarr13);
}

static FortranDataDef f2py_qgarr16_def[] = {
  {"cc",2,{{2,3}},NPY_DOUBLE},
  {"iddp",1,{{208}},NPY_INT},
  {"iddt",1,{{208}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr16(char *cc,char *iddp,char *iddt) {
  int i_f2py=0;
  f2py_qgarr16_def[i_f2py++].data = cc;
  f2py_qgarr16_def[i_f2py++].data = iddp;
  f2py_qgarr16_def[i_f2py++].data = iddt;
}
extern void F_FUNC(f2pyinitqgarr16,F2PYINITQGARR16)(void(*)(char*,char*,char*));
static void f2py_init_qgarr16(void) {
  F_FUNC(f2pyinitqgarr16,F2PYINITQGARR16)(f2py_setup_qgarr16);
}

static FortranDataDef f2py_qgarr23_def[] = {
  {"bbpom",1,{{1000}},NPY_DOUBLE},
  {"vvxpom",1,{{1000}},NPY_DOUBLE},
  {"bpompr",2,{{900,208}},NPY_DOUBLE},
  {"bpomtg",2,{{900,208}},NPY_DOUBLE},
  {"vvxpr",2,{{900,208}},NPY_DOUBLE},
  {"vvxtg",2,{{900,208}},NPY_DOUBLE},
  {"xpompr",2,{{900,208}},NPY_DOUBLE},
  {"xpomtg",2,{{900,208}},NPY_DOUBLE},
  {"xpopin",2,{{900,1000}},NPY_DOUBLE},
  {"xpomin",2,{{900,1000}},NPY_DOUBLE},
  {"vvxin",2,{{900,1000}},NPY_DOUBLE},
  {"bpomin",2,{{900,1000}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_qgarr23(char *bbpom,char *vvxpom,char *bpompr,char *bpomtg,char *vvxpr,char *vvxtg,char *xpompr,char *xpomtg,char *xpopin,char *xpomin,char *vvxin,char *bpomin) {
  int i_f2py=0;
  f2py_qgarr23_def[i_f2py++].data = bbpom;
  f2py_qgarr23_def[i_f2py++].data = vvxpom;
  f2py_qgarr23_def[i_f2py++].data = bpompr;
  f2py_qgarr23_def[i_f2py++].data = bpomtg;
  f2py_qgarr23_def[i_f2py++].data = vvxpr;
  f2py_qgarr23_def[i_f2py++].data = vvxtg;
  f2py_qgarr23_def[i_f2py++].data = xpompr;
  f2py_qgarr23_def[i_f2py++].data = xpomtg;
  f2py_qgarr23_def[i_f2py++].data = xpopin;
  f2py_qgarr23_def[i_f2py++].data = xpomin;
  f2py_qgarr23_def[i_f2py++].data = vvxin;
  f2py_qgarr23_def[i_f2py++].data = bpomin;
}
extern void F_FUNC(f2pyinitqgarr23,F2PYINITQGARR23)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_qgarr23(void) {
  F_FUNC(f2pyinitqgarr23,F2PYINITQGARR23)(f2py_setup_qgarr23);
}

static FortranDataDef f2py_qgarr46_def[] = {
  {"iconab",2,{{208,208}},NPY_INT},
  {"icona",1,{{208}},NPY_INT},
  {"iconb",1,{{208}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr46(char *iconab,char *icona,char *iconb) {
  int i_f2py=0;
  f2py_qgarr46_def[i_f2py++].data = iconab;
  f2py_qgarr46_def[i_f2py++].data = icona;
  f2py_qgarr46_def[i_f2py++].data = iconb;
}
extern void F_FUNC(f2pyinitqgarr46,F2PYINITQGARR46)(void(*)(char*,char*,char*));
static void f2py_init_qgarr46(void) {
  F_FUNC(f2pyinitqgarr46,F2PYINITQGARR46)(f2py_setup_qgarr46);
}

static FortranDataDef f2py_qgarr55_def[] = {
  {"nwt",0,{{-1}},NPY_INT},
  {"nwp",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr55(char *nwt,char *nwp) {
  int i_f2py=0;
  f2py_qgarr55_def[i_f2py++].data = nwt;
  f2py_qgarr55_def[i_f2py++].data = nwp;
}
extern void F_FUNC(f2pyinitqgarr55,F2PYINITQGARR55)(void(*)(char*,char*));
static void f2py_init_qgarr55(void) {
  F_FUNC(f2pyinitqgarr55,F2PYINITQGARR55)(f2py_setup_qgarr55);
}

static FortranDataDef f2py_qgarr56_def[] = {
  {"nspec",0,{{-1}},NPY_INT},
  {"nspect",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_qgarr56(char *nspec,char *nspect) {
  int i_f2py=0;
  f2py_qgarr56_def[i_f2py++].data = nspec;
  f2py_qgarr56_def[i_f2py++].data = nspect;
}
extern void F_FUNC(f2pyinitqgarr56,F2PYINITQGARR56)(void(*)(char*,char*));
static void f2py_init_qgarr56(void) {
  F_FUNC(f2pyinitqgarr56,F2PYINITQGARR56)(f2py_setup_qgarr56);
}

static FortranDataDef f2py_jdiff_def[] = {
  {"bdiff",0,{{-1}},NPY_DOUBLE},
  {"jdiff",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_jdiff(char *bdiff,char *jdiff) {
  int i_f2py=0;
  f2py_jdiff_def[i_f2py++].data = bdiff;
  f2py_jdiff_def[i_f2py++].data = jdiff;
}
extern void F_FUNC(f2pyinitjdiff,F2PYINITJDIFF)(void(*)(char*,char*));
static void f2py_init_jdiff(void) {
  F_FUNC(f2pyinitjdiff,F2PYINITJDIFF)(f2py_setup_jdiff);
}

static FortranDataDef f2py_c2evt_def[] = {
  {"ng1evt",0,{{-1}},NPY_INT},
  {"ng2evt",0,{{-1}},NPY_INT},
  {"rglevt",0,{{-1}},NPY_FLOAT},
  {"sglevt",0,{{-1}},NPY_FLOAT},
  {"eglevt",0,{{-1}},NPY_FLOAT},
  {"fglevt",0,{{-1}},NPY_FLOAT},
  {"ikoevt",0,{{-1}},NPY_INT},
  {"typevt",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_c2evt(char *ng1evt,char *ng2evt,char *rglevt,char *sglevt,char *eglevt,char *fglevt,char *ikoevt,char *typevt) {
  int i_f2py=0;
  f2py_c2evt_def[i_f2py++].data = ng1evt;
  f2py_c2evt_def[i_f2py++].data = ng2evt;
  f2py_c2evt_def[i_f2py++].data = rglevt;
  f2py_c2evt_def[i_f2py++].data = sglevt;
  f2py_c2evt_def[i_f2py++].data = eglevt;
  f2py_c2evt_def[i_f2py++].data = fglevt;
  f2py_c2evt_def[i_f2py++].data = ikoevt;
  f2py_c2evt_def[i_f2py++].data = typevt;
}
extern void F_FUNC(f2pyinitc2evt,F2PYINITC2EVT)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_c2evt(void) {
  F_FUNC(f2pyinitc2evt,F2PYINITC2EVT)(f2py_setup_c2evt);
}

static FortranDataDef f2py_arr3_def[] = {
  {"x1",1,{{7}},NPY_DOUBLE},
  {"a1",1,{{7}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_arr3(char *x1,char *a1) {
  int i_f2py=0;
  f2py_arr3_def[i_f2py++].data = x1;
  f2py_arr3_def[i_f2py++].data = a1;
}
extern void F_FUNC(f2pyinitarr3,F2PYINITARR3)(void(*)(char*,char*));
static void f2py_init_arr3(void) {
  F_FUNC(f2pyinitarr3,F2PYINITARR3)(f2py_setup_arr3);
}

static FortranDataDef f2py_arr4_def[] = {
  {"x4",1,{{2}},NPY_DOUBLE},
  {"a4",1,{{2}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_arr4(char *x4,char *a4) {
  int i_f2py=0;
  f2py_arr4_def[i_f2py++].data = x4;
  f2py_arr4_def[i_f2py++].data = a4;
}
extern void F_FUNC(f2pyinitarr4,F2PYINITARR4)(void(*)(char*,char*));
static void f2py_init_arr4(void) {
  F_FUNC(f2pyinitarr4,F2PYINITARR4)(f2py_setup_arr4);
}

static FortranDataDef f2py_arr5_def[] = {
  {"x5",1,{{2}},NPY_DOUBLE},
  {"a5",1,{{2}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_arr5(char *x5,char *a5) {
  int i_f2py=0;
  f2py_arr5_def[i_f2py++].data = x5;
  f2py_arr5_def[i_f2py++].data = a5;
}
extern void F_FUNC(f2pyinitarr5,F2PYINITARR5)(void(*)(char*,char*));
static void f2py_init_arr5(void) {
  F_FUNC(f2pyinitarr5,F2PYINITARR5)(f2py_setup_arr5);
}

static FortranDataDef f2py_arr8_def[] = {
  {"x2",1,{{4}},NPY_DOUBLE},
  {"a2",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_arr8(char *x2,char *a2) {
  int i_f2py=0;
  f2py_arr8_def[i_f2py++].data = x2;
  f2py_arr8_def[i_f2py++].data = a2;
}
extern void F_FUNC(f2pyinitarr8,F2PYINITARR8)(void(*)(char*,char*));
static void f2py_init_arr8(void) {
  F_FUNC(f2pyinitarr8,F2PYINITARR8)(f2py_setup_arr8);
}

static FortranDataDef f2py_arr9_def[] = {
  {"x9",1,{{3}},NPY_DOUBLE},
  {"a9",1,{{3}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_arr9(char *x9,char *a9) {
  int i_f2py=0;
  f2py_arr9_def[i_f2py++].data = x9;
  f2py_arr9_def[i_f2py++].data = a9;
}
extern void F_FUNC(f2pyinitarr9,F2PYINITARR9)(void(*)(char*,char*));
static void f2py_init_arr9(void) {
  F_FUNC(f2pyinitarr9,F2PYINITARR9)(f2py_setup_arr9);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"qgini",-1,{{-1}},0,(char *)F_FUNC(qgini,QGINI),(f2py_init_func)f2py_rout__qgsII04_qgini,doc_f2py_rout__qgsII04_qgini},
    {"qgconf",-1,{{-1}},0,(char *)F_FUNC(qgconf,QGCONF),(f2py_init_func)f2py_rout__qgsII04_qgconf,doc_f2py_rout__qgsII04_qgconf},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_qgsII04",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__qgsII04(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _qgsII04_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _qgsII04 (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.23.5");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_qgsII04' is auto-generated with f2py (version:1.23.5).\nFunctions:\n"
"    qgini(e0n,icp0,iap,iat)\n"
"    qgconf()\n"
"COMMON blocks:\n""  /qgarr1/ ia(2),icz,icp\n""  /qgarr2/ scm,wp0,wm0\n""  /qgarr4/ ey0(3)\n""  /qgarr5/ rnuc(2),wsnuc(2),wbnuc(2),anorm,cr1(2),cr2(2),cr3(2)\n""  /qgarr6/ pi,bm,amws\n""  /qgarr7/ xa(208,3),xb(208,3),b\n""  /qgarr10/ am(7),ammu\n""  /qgarr15/ fp(3),rq(2,3),cd(2,3),gsoft(3)\n""  /qgarr17/ dels,alfp,sigs,rr,r3p,g3p,delh,sgap\n""  /qgarr43/ moniou\n""  /arr1/ trnuc(56),twsnuc(56),twbnuc(56)\n""  /qgdebug/ debug\n""  /qgsiinex1/ xan(208,3),xbn(208,3),bqgs,bmaxqgs,bmaxnex,bminnex\n""  /qgarr9/ iwp(208),iwt(208),lqa(208),lqb(208),iprcn(208),itgcn(208),ias(1000),ibs(1000),nqs(1000),npompr(1000),npomtg(1000),npomin(1000),nnpr(900,1000),nntg(900,1000),ilpr(900,1000),iltg(900,1000),lnpr(900,1000),lntg(900,1000),nbpi(900,208),nbti(900,208),idnpi(900,208),idnti(900,208),nppi(900,208),npti(900,208),nlpi(900,208),nlti(900,208)\n""  /qgarr11/ b10\n""  /qgarr12/ nsp\n""  /qgarr13/ nsf,iaf(208)\n""  /qgarr16/ cc(2,3),iddp(208),iddt(208)\n""  /qgarr23/ bbpom(1000),vvxpom(1000),bpompr(900,208),bpomtg(900,208),vvxpr(900,208),vvxtg(900,208),xpompr(900,208),xpomtg(900,208),xpopin(900,1000),xpomin(900,1000),vvxin(900,1000),bpomin(900,1000)\n""  /qgarr46/ iconab(208,208),icona(208),iconb(208)\n""  /qgarr55/ nwt,nwp\n""  /qgarr56/ nspec,nspect\n""  /jdiff/ bdiff,jdiff\n""  /c2evt/ ng1evt,ng2evt,rglevt,sglevt,eglevt,fglevt,ikoevt,typevt\n""  /arr3/ x1(7),a1(7)\n""  /arr4/ x4(2),a4(2)\n""  /arr5/ x5(2),a5(2)\n""  /arr8/ x2(4),a2\n""  /arr9/ x9(3),a9(3)\n"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.23.5");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _qgsII04_error = PyErr_NewException ("_qgsII04.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__qgsII04_error", _qgsII04_error);
    Py_DECREF(_qgsII04_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  tmp = PyFortranObject_New(f2py_qgarr1_def,f2py_init_qgarr1);
  F2PyDict_SetItemString(d, "qgarr1", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr2_def,f2py_init_qgarr2);
  F2PyDict_SetItemString(d, "qgarr2", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr4_def,f2py_init_qgarr4);
  F2PyDict_SetItemString(d, "qgarr4", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr5_def,f2py_init_qgarr5);
  F2PyDict_SetItemString(d, "qgarr5", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr6_def,f2py_init_qgarr6);
  F2PyDict_SetItemString(d, "qgarr6", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr7_def,f2py_init_qgarr7);
  F2PyDict_SetItemString(d, "qgarr7", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr10_def,f2py_init_qgarr10);
  F2PyDict_SetItemString(d, "qgarr10", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr15_def,f2py_init_qgarr15);
  F2PyDict_SetItemString(d, "qgarr15", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr17_def,f2py_init_qgarr17);
  F2PyDict_SetItemString(d, "qgarr17", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr43_def,f2py_init_qgarr43);
  F2PyDict_SetItemString(d, "qgarr43", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_arr1_def,f2py_init_arr1);
  F2PyDict_SetItemString(d, "arr1", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgdebug_def,f2py_init_qgdebug);
  F2PyDict_SetItemString(d, "qgdebug", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgsiinex1_def,f2py_init_qgsiinex1);
  F2PyDict_SetItemString(d, "qgsiinex1", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr9_def,f2py_init_qgarr9);
  F2PyDict_SetItemString(d, "qgarr9", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr11_def,f2py_init_qgarr11);
  F2PyDict_SetItemString(d, "qgarr11", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr12_def,f2py_init_qgarr12);
  F2PyDict_SetItemString(d, "qgarr12", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr13_def,f2py_init_qgarr13);
  F2PyDict_SetItemString(d, "qgarr13", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr16_def,f2py_init_qgarr16);
  F2PyDict_SetItemString(d, "qgarr16", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr23_def,f2py_init_qgarr23);
  F2PyDict_SetItemString(d, "qgarr23", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr46_def,f2py_init_qgarr46);
  F2PyDict_SetItemString(d, "qgarr46", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr55_def,f2py_init_qgarr55);
  F2PyDict_SetItemString(d, "qgarr55", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_qgarr56_def,f2py_init_qgarr56);
  F2PyDict_SetItemString(d, "qgarr56", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_jdiff_def,f2py_init_jdiff);
  F2PyDict_SetItemString(d, "jdiff", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_c2evt_def,f2py_init_c2evt);
  F2PyDict_SetItemString(d, "c2evt", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_arr3_def,f2py_init_arr3);
  F2PyDict_SetItemString(d, "arr3", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_arr4_def,f2py_init_arr4);
  F2PyDict_SetItemString(d, "arr4", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_arr5_def,f2py_init_arr5);
  F2PyDict_SetItemString(d, "arr5", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_arr8_def,f2py_init_arr8);
  F2PyDict_SetItemString(d, "arr8", tmp);
  Py_DECREF(tmp);
  tmp = PyFortranObject_New(f2py_arr9_def,f2py_init_arr9);
  F2PyDict_SetItemString(d, "arr9", tmp);
  Py_DECREF(tmp);
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_qgsII04");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
