C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.23.5)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinits_plist(setupfunc)
      external setupfunc
      real p(8000,5)
      integer llist(8000)
      integer np
      common /s_plist/ p,llist,np
      call setupfunc(p,llist,np)
      end

      subroutine f2pyinits_run(setupfunc)
      external setupfunc
      real sqs
      real s
      real ptmin
      real xmin
      real zmin
      integer kb
      integer kt
      common /s_run/ sqs,s,ptmin,xmin,zmin,kb,kt
      call setupfunc(sqs,s,ptmin,xmin,zmin,kb,kt)
      end

      subroutine f2pyinits_debug(setupfunc)
      external setupfunc
      integer ncall
      integer ndebug
      integer lun
      common /s_debug/ ncall,ndebug,lun
      call setupfunc(ncall,ndebug,lun)
      end

      subroutine f2pyinits_chist(setupfunc)
      external setupfunc
      real x1j(1400)
      real x2j(1400)
      real x1jsum(20)
      real x2jsum(20)
      real ptjet(1400)
      real phijet(1400)
      integer nnpjet(1400)
      integer nnpstr(40)
      integer nnsof(20)
      integer nnjet(20)
      integer jdif(20)
      integer nw
      integer njet
      integer nsof
      common /s_chist/ x1j,x2j,x1jsum,x2jsum,ptjet,phijet,nnpjet,n
     &npstr,nnsof,nnjet,jdif,nw,njet,nsof
      call setupfunc(x1j,x2j,x1jsum,x2jsum,ptjet,phijet,nnpjet,nnp
     &str,nnsof,nnjet,jdif,nw,njet,nsof)
      end

      subroutine f2pyinits_ccstr(setupfunc)
      external setupfunc
      real x1(40)
      real x2(40)
      real pxb(40)
      real pyb(40)
      real pxt(40)
      real pyt(40)
      integer iflb(40)
      integer iflt(40)
      common /s_ccstr/ x1,x2,pxb,pyb,pxt,pyt,iflb,iflt
      call setupfunc(x1,x2,pxb,pyb,pxt,pyt,iflb,iflt)
      end

      subroutine f2pyinits_cldif(setupfunc)
      external setupfunc
      integer ldiff
      common /s_cldif/ ldiff
      call setupfunc(ldiff)
      end

      subroutine f2pyinits_cqdis(setupfunc)
      external setupfunc
      real ppt0(33)
      real ptflag
      common /s_cqdis/ ppt0,ptflag
      call setupfunc(ppt0,ptflag)
      end

      subroutine f2pyinits_cutoff(setupfunc)
      external setupfunc
      real str_mass_val
      real str_mass_sea
      common /s_cutoff/ str_mass_val,str_mass_sea
      call setupfunc(str_mass_val,str_mass_sea)
      end

      subroutine f2pyinits_plist1(setupfunc)
      external setupfunc
      integer llist1(8000)
      common /s_plist1/ llist1
      call setupfunc(llist1)
      end

      subroutine f2pyinits_cnam(setupfunc)
      external setupfunc
      character namp(50,6)
      common /s_cnam/ namp
      call setupfunc(namp)
      end

      subroutine f2pyinits_chp(setupfunc)
      external setupfunc
      integer ichp(49)
      integer istr(49)
      integer ibar(49)
      common /s_chp/ ichp,istr,ibar
      call setupfunc(ichp,istr,ibar)
      end

      subroutine f2pyinits_czdis(setupfunc)
      external setupfunc
      real fa
      real fb0
      common /s_czdis/ fa,fb0
      call setupfunc(fa,fb0)
      end

      subroutine f2pyinits_czdiss(setupfunc)
      external setupfunc
      real fas1
      real fas2
      common /s_czdiss/ fas1,fas2
      call setupfunc(fas1,fas2)
      end

      subroutine f2pyinits_czlead(setupfunc)
      external setupfunc
      real clead
      real flead
      common /s_czlead/ clead,flead
      call setupfunc(clead,flead)
      end

      subroutine f2pyinits_cpspl(setupfunc)
      external setupfunc
      real cchik(3,9)
      common /s_cpspl/ cchik
      call setupfunc(cchik)
      end

      subroutine f2pyinits_cflafr(setupfunc)
      external setupfunc
      real par(20)
      integer ipar(10)
      common /s_cflafr/ par,ipar
      call setupfunc(par,ipar)
      end

      subroutine f2pyinitckfrag(setupfunc)
      external setupfunc
      integer kodfrag
      common /ckfrag/ kodfrag
      call setupfunc(kodfrag)
      end


